### ISSUE TITLE
蓝叠Hyper-V版，点击Link Start之后出现连接模拟器，随后闪退

### ISSUE THREAD

**Issue by PianCat** [MistEO/MeoAssistantArknights#100]
蓝叠Hyper-V版，点击Link Start之后出现连接模拟器，随后闪退

设备为AMD处理器，支持AVX指令集，也更换了NoAVX版本的OCR，系统为Windows 11（不知道有没有影响

[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7833551/asst.log)

**Comment by MistEO** [comment]
有填写过 bluestacks.conf 么，看起来像是解析这个文件的时候崩了，是不是路径不对_(:з」∠)_

**Comment by PianCat** [comment]
> 有填写过 bluestacks.conf 么，看起来像是解析这个文件的时候崩了，是不是路径不对_(:з」∠)_

填写了，不过我换蓝叠4Hyper-V版本了，暂时不知道哪里有bluestacks.conf，于是手动填写ADB啦。

**Comment by PianCat** [comment]
[BSTweakerCatchTheBlueStacksADBPortLog.txt](https://github.com/MistEO/MeoAssistantArknights/files/7833891/BSTweakerCatchTheBlueStacksADBPortLog.txt)

**Comment by PianCat** [comment]
不过蓝叠的话，要抓ADB Port最好还是做一下多模拟器区分这样
会好一些

**Comment by MistEO** [comment]
> 有填写过 bluestacks.conf 么，看起来像是解析这个文件的时候崩了，是不是路径不对_(:з」∠)_

群里有小伙伴出现了同样的问题，日志一模一样。基本确定是文件路径有问题，请检查一下~
