### ISSUE TITLE
会客室是否可以添加一个自动开启线索交流和优先将线索替换为好友线索的功能？

### ISSUE THREAD

**Issue by PianCat** [MistEO/MeoAssistantArknights#101]
会客室的线索交流在可以开启的时候，下面的开启交流按钮会点亮。
好友送来的线索在挂在会客室线索列表里面的时候右上角会有日期提醒（红框

**Comment by MistEO** [comment]
- 自动开启线索交流，当前就是有的，如果没开那就是有 bug _(:з」∠)_
- 线索会自动使用最下面的那个，一般来说就是时间最短的，除非有好多可以翻页

**Comment by MistEO** [comment]
话说现在能用了吗，怎么解决的呀？

**Comment by PianCat** [comment]
> 

怪怪的bug，我这边看起来没有生效，没看到它换线索去开交流

**Comment by PianCat** [comment]
> 话说现在能用了吗，怎么解决的呀？

手动填写ADB端口了，我刚刚去看了一下一个针对蓝叠的工具箱的ADB端口实现方案，我发回原Issue那里去了，我觉得作者可以参考一下整一下

**Comment by MistEO** [comment]
新版本应该已经解决了偶现的不开线索交流问题了，请更新体验~
