### ISSUE TITLE
补充体力bug

### ISSUE THREAD

**Issue by sftime100** [MistEO/MeoAssistantArknights#103]
mumu模拟器，执行刷理智时，在既没有体力药也没有石头的情况下，会停在吃石头界面
![image](https://user-images.githubusercontent.com/81544236/148662954-bec8e23f-99ee-409e-a383-ad7e5f532bd0.png)
后续操作都会因出错而停止

**Comment by MistEO** [comment]
[测试版本](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.7.1) 已修复，请期待正式版本~
