### ISSUE TITLE
信用商店购物bug

### ISSUE THREAD

**Issue by maidangdang1** [MistEO/MeoAssistantArknights#104]
我用的是蓝叠 Hyper-V版，最近一直卡在购物这里，来看看是啥原因🤔
![image](https://user-images.githubusercontent.com/46847241/148673427-835826ce-1c9b-4688-9b8a-dba6c4c1785c.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7834618/asst.log)

**Comment by MistEO** [comment]
已知问题，测试版已经修复过了，请期待正式版本~
