### ISSUE TITLE
公招点选TAG时出现闪退

### ISSUE THREAD

**Issue by 1756444066** [MistEO/MeoAssistantArknights#106]
公招时自动点击“快速复活”tag后出现闪退
log文件：http://www.ljxstudio.com/files/asst.log

**Comment by MistEO** [comment]
[测试版本](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.7.1) 已尝试修复，不知道有没有效果，麻烦帮忙再反馈下 _(:з」∠)_
