### ISSUE TITLE
掉落材料不识别

### ISSUE THREAD

**Issue by cglcv** [MistEO/MeoAssistantArknights#108]
RT，刷WR-10时，掉落统计一直显示无，但游戏中显示有固原岩组掉落
模拟器：蓝叠5，端口5556，使用自定义ADB（5555被华为移动应用引擎占用）
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7851539/asst.log)

**Comment by cglcv** [comment]
才发现使用的版本过老（2.5.2），一会儿再试试，没理智了

**Comment by cglcv** [comment]
试完了，还是不行orz

**Comment by MistEO** [comment]
- 需要更新关卡数据资源才可以识别
- 项目配置了 OTA 自动更新功能，但受限于部分网络环境影响，可以尝试在软件设置中填写 proxy 后重新打开软件，会自动更新的。或者直接使用 v2.7.3 测试版本，已经集成了新的关卡资源

**Comment by cglcv** [comment]
拿芯片本试了一次，确实是关卡资源问题
