### ISSUE TITLE
结算界面闪退

### ISSUE THREAD

**Issue by Blood-thirsted** [MistEO/MeoAssistantArknights#110]
刷的WR-10，第一把识别完后提交企鹅物流失败，第二把到结算界面就直接闪退了
用的mumu模拟器，win11系统
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7852161/asst.log)

**Comment by MistEO** [comment]
好复现么？能不能帮忙截个游戏的原图看一下_(:з」∠)_

**Comment by Blood-thirsted** [comment]
> 好复现么？能不能帮忙截个游戏的原图看一下_(:з」∠)_

啊这，现在没理智了。就是打完后的结算界面那

**Comment by MistEO** [comment]
有点问题，资源和版本不对应，不知道是不是更新出问题了。重新手动下载一个试试看？

**Comment by MistEO** [comment]
更新了一个 [v2.7.4](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.7.4) ，不知道有没有效果，再帮忙看看_(:з」∠)_

**Comment by Blood-thirsted** [comment]
> 更新了一个 [v2.7.4](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.7.4) ，不知道有没有效果，再帮忙看看_(:з」∠)_

能用了，好耶ヾ(✿ﾟ▽ﾟ)ノ
