### ISSUE TITLE
只选碎石程序直接完成

### ISSUE THREAD

**Issue by vicasong** [MistEO/MeoAssistantArknights#111]
有理智药，但不选使用理智药，只选碎石，任务直接完成了

**Comment by vicasong** [comment]
还有，“画中人”掉落识别全是：无？
![截图_20220112201939](https://user-images.githubusercontent.com/21325582/149139163-69243c7f-0c27-4dd8-b29c-51ed4335eb64.png)


日志文件：
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7854489/asst.log)

**Comment by MistEO** [comment]
> 主界面上的 吃理智、吃石头、指定次数 三个选项为短路开关，即三个选项中的任一条件达到，均会视为任务完成，停止刷理智。
举例1：设置 吃理智药 : 999、吃石头 : 10、指定次数 : 1。则在刷完 一次 后，由于满足了 指定次数:1 的条件，视为任务完成，停止刷理智。
举例2：不勾选 吃理智药、不勾选 吃石头，设置 指定次数 : 100。则在当前可用理智全部刷完后（可能只刷了几次），由于满足了 不吃理智药、不吃石头 的条件，视为任务完成，停止刷理智。

**Comment by vicasong** [comment]
是呀，我首先试了只勾选吃石头，不勾选吃药和指定次数，按理应该碎一定数量的石头吧，结果直接完成

**Comment by vicasong** [comment]
我懂了，补充理智至少要选吃药是吧

**Comment by MistEO** [comment]
[v2.7.4](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.7.4) 改了点界面小逻辑，勾选吃石头会自动把吃理智药也勾上 2333
