### ISSUE TITLE
蓝叠最新国际版闪退

### ISSUE THREAD

**Issue by feiqingbiss** [MistEO/MeoAssistantArknights#112]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7856207/asst.log)
[MeoAsstGui.exe.11476.zip](https://github.com/MistEO/MeoAssistantArknights/files/7856214/MeoAsstGui.exe.11476.zip)
一个dump文件一个log文件，蓝叠最新国际版，A7 64 A9 BETA 64两个版本都是直接运行后闪退

**Comment by MistEO** [comment]
> A7 64 A9 BETA 64

这个是啥_(:з」∠)_

另外是点击了开始之后才闪退的么？还是一启动就闪退

**Comment by Puqns67** [comment]
点了开始后才会崩溃

**Comment by MistEO** [comment]
[隔壁 issue](https://github.com/MistEO/MeoAssistantArknights/issues/113#issuecomment-1012358150) 的大佬帮忙找到问题原因，这类的闪退问题会尝试在下个版本全部解决掉 ✿✿ヽ(°▽°)ノ✿

**Comment by MistEO** [comment]
请尝试 [v2.7.5](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.7.5) ~

**Comment by Puqns67** [comment]
问题已修正
