### ISSUE TITLE
Android AVD 启动任何任务后闪退

### ISSUE THREAD

**Issue by mslxl** [MistEO/MeoAssistantArknights#113]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7862170/asst.log)

AVD 信息：Resolution 2560x1440:hdpi Android11 X86
最后一个能够正常运行的版本v2.6.6

感觉是压缩或者截屏的问题

手动运行命令的结果:
* `adb -s 127.0.0.1 exec-out "screencap" > screencap.raw` ：[screencap.zip](https://github.com/MistEO/MeoAssistantArknights/files/7862229/screencap.zip) （已压缩）

* `adb -s 127.0.0.1 exec-out "screencap -p" > screencap.png` ：[screencap.png](https://user-images.githubusercontent.com/11132880/149319579-0a24c3e8-f8d4-445e-8508-192ceb38dd57.png)
* `adb  -s 127.0.0.1 exec-out "screencap | gzip -1“  > screencap.gz` ： [screencap.gz](https://github.com/MistEO/MeoAssistantArknights/files/7862247/screencap.gz)

**Comment by mslxl** [comment]
按照[夜神模拟器 安卓 9](https://github.com/MistEO/MeoAssistantArknights/blob/master/docs/%E6%A8%A1%E6%8B%9F%E5%99%A8%E6%94%AF%E6%8C%81.md#%E5%A4%9C%E7%A5%9E%E6%A8%A1%E6%8B%9F%E5%99%A8-%E5%AE%89%E5%8D%93-9)试了一下，可以运行

<hr/>

另外我研究了一下，高版本的安卓截出的图片将 dataspace 也写入了截图，导致原来图片的内容在 12 个字节后，新版本在16个字节后

[旧版本 screencap 代码 191行到193行](https://android.googlesource.com/platform/frameworks/base/+/android-4.3_r2.3/cmds/screencap/screencap.cpp):


[新版本 screencap 代码 243行到246行](https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-12.0.0_r26/cmds/screencap/screencap.cpp)

我验证了下似乎就是因为这个问题导致 MAA 不能正确识别图片

`adb exec-out screencap | hexdump -C | head :`
```raw
00000000  00 0a 00 00 a0 05 00 00  01 00 00 00 01 00 00 00  |................|
00000010  98 63 71 ff 98 63 71 ff  98 63 71 ff 98 63 71 ff  |.cq..cq..cq..cq.|
```
前16字节正好对应图片信息，简单的用 opencv 验证了下，发现的确如此
```python
import cv2
import numpy as np

with open('screen.raw', 'rb') as file:
    buffer = file.read()[16:]

array = np.frombuffer(buffer, np.uint8).reshape(1440, 2560, 4)
image = cv2.cvtColor(array, cv2.COLOR_BGRA2RGB)
cv2.imshow("image", image)
cv2.waitKey()
```
这可能就是MAA闪退的原因了

~所以为什么不用screencap -p呢~

**Comment by MistEO** [comment]
screencap -p 太慢了，在我的机器上，`screencap -p` 约需要 700ms; `screencap | gzip -1` 只需要 200ms. 数据体积是差不多大的

**Comment by MistEO** [comment]
如果明确了是文件头的问题的话那确实好办了太多了，感谢大佬。很多模拟器失败的问题都有解了

**Comment by MistEO** [comment]
请尝试 [v2.7.5](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.7.5) ~

**Comment by mslxl** [comment]
没问题了👍
