### ISSUE TITLE
新版更新后基建无限循环

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#114]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7862808/asst.log)
和当年的老问题基本一样，但不同的是他会在制造站0123重复循环，就是不换人

**Comment by MistEO** [comment]
> MuMu 模拟器
> 支持。但是可能会
> - 一直连接出错：暂时不知道是什么原因，可尝试使用自定义连接
> - 卡在主界面无法识别，过一会提示任务出错：和 MuMu 的渲染方式有关，推荐换模拟器（

看起来像是这里的问题 2, 不介意的话可以换个模拟器试试

**Comment by guojunyu196** [comment]
用的是逍遥模拟器，我换个模拟器试试

**Comment by guojunyu196** [comment]
离谱奥，改变模拟器窗口大小之后正常运行了(:з」∠)_

**Comment by MistEO** [comment]
如果现在使用没有问题，那 issue 我就关掉了哦_(:з」∠)_
