### ISSUE TITLE
基建存在异格干员时会卡住导致失败

### ISSUE THREAD

**Issue by RWoxiN** [MistEO/MeoAssistantArknights#118]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7882843/asst.log)

情境：此时，异格炎熔 0 心情在控制中心，炎熔满心情无所事事。

步骤：
1. 控制中心中的 0 心情异格炎熔被下，替换成其他干员。此时 0 心情异格炎熔和满心情炎熔均无所事事。
2. 发电站满心情炎熔开始上班。因两个炎熔均无所事事，故没有报错。
3. 在宿舍逻辑里，0 心情炎熔被选中进入宿舍，此时弹出基建换班确认的提示框，就此卡住导致失败。
![image](https://user-images.githubusercontent.com/78133217/149795521-b435fa79-bc0c-43fd-89b6-56c6a44ff36b.png)

**Comment by MistEO** [comment]
https://github.com/MistEO/MeoAssistantArknights/issues/56 已知问题。目前临时解决方案是 ban 掉了炎狱炎熔，控制中枢是不会使用她的。也就没有心情低被替换到宿舍的可能了_(:з」∠)_

但是手动换的还是解决不了，没啥好办法，当前的架构解决不了，作为长期计划了 orz

**Comment by MistEO** [comment]
想到一个主意，直接点一下确认，把她换下来，然后界面上显示个报错啥的。之后先这样改改

**Comment by RWoxiN** [comment]
> #56 已知问题。目前临时解决方案是 ban 掉了炎狱炎熔，控制中枢是不会使用她的。也就没有心情低被替换到宿舍的可能了_(:з」∠)_
> 
> 但是手动换的还是解决不了，没啥好办法，当前的架构解决不了，作为长期计划了 orz

我的炎狱炎熔还是 MAA 放进控制中枢的诶，不是手动换的。

**Comment by MistEO** [comment]
[v2.7.8](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.7.8) 已修复卡住的问题，并添加对应的错误提示。请尝试~
