### ISSUE TITLE
基建换班选人异常

### ISSUE THREAD

**Issue by mjft** [MistEO/MeoAssistantArknights#119]
选人的时候清空选择后往右移，移一会儿后显示白屏，自动退出变成循环

![4df2e9d29babbfef3b2281c5fa8b59e](https://user-images.githubusercontent.com/79824533/149815247-be9ff6d6-a3a4-447e-829e-4258288aa0e8.png)

[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7883800/asst.log)

**Comment by MistEO** [comment]
这个应该是游戏本身的 bug ? MAA 无能为力了_(:з」∠)_

可以试试反馈给鹰角，两百合成玉警告（

**Comment by mjft** [comment]
阿哲，自己手动选人没问题的，用助手自动滑才会这样

**Comment by MistEO** [comment]
> 阿哲，自己手动选人没问题的，用助手自动滑才会这样

是游戏问题。助手是非侵入式的，仅使用了 adb input 和 adb swipe

**Comment by mjft** [comment]
重启模拟器可以运行了，之前修改过窗口大小0.0
