### ISSUE TITLE
能不能提供一个材料管理系统

### ISSUE THREAD

**Issue by MarsCloud** [MistEO/MeoAssistantArknights#12]
显示全干员专三的需求（少哪些材料，溢出哪些材料），识别仓库材料，识别干员技能专精等级（做不到的话可以让用户手动设置），然后可以由用户选择接下来要专精的技能以及刷图建议，这些信息有一部分可以从企鹅物流获得

**Comment by MistEO** [comment]
想了想工程量非常大。。最近都在搞基建，有空再做吧_(:з」∠)_

下次一定！

**Comment by MarsCloud** [comment]
> 想了想工程量非常大。。最近都在搞基建，有空再做吧_(:з」∠)_
> 
> 下次一定！

其实我就是单纯提一个未来可以做的优化方向而已，而且平时自己也在设想要是有这么一个辅助工具就好了……

**Comment by MistEO** [comment]
与当前软件的发展方向偏差过大，应该是不会做了_(:з」∠)_

**Comment by zzyyyl** [comment]
这是不是已经 on progress 了（？
Link to #882
