### ISSUE TITLE
新版本使用时经常闪退

### ISSUE THREAD

**Issue by 524388475** [MistEO/MeoAssistantArknights#120]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7885529/asst.log)

夜神模拟器在使用的时候会出现闪退情况，不知道为啥（截图咱也截不到啊，咱啥也没动就自己闪退了）

**Comment by MistEO** [comment]
闪退之后游戏是卡在了关卡掉落结算的界面么？

**Comment by 524388475** [comment]
是这样的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月18日(星期二) 上午9:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MistEO/MeoAssistantArknights] 新版本使用时经常闪退 (Issue #120)





 
闪退之后游戏是卡在了关卡掉落结算的界面么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MistEO** [comment]
掉落识别之前加了龙门币啥的，好像确实有问题 orz

下次再遇到帮忙截一张游戏界面的原图吧，我离线跑下看看能不能复现_(:з」∠)_

**Comment by 524388475** [comment]
好的好的，这个应该好截图QWQ

**Comment by 524388475** [comment]
![B51{B 7V_GW{ AXFRR09TUW](https://user-images.githubusercontent.com/72139364/149872294-14752cab-5fab-4c8a-bbc5-8303b0df051f.png)
已经有截图了（经过我多达3次的测试发现，每次只要有合金出现，脚本就崩了QAQ）

**Comment by MistEO** [comment]
> ![B51{B 7V_GW{ AXFRR09TUW](https://user-images.githubusercontent.com/72139364/149872294-14752cab-5fab-4c8a-bbc5-8303b0df051f.png) 已经有截图了（经过我多达3次的测试发现，每次只要有合金出现，脚本就崩了QAQ）

_(:з」∠)_要游戏原图，模拟器自带的截图工具这种的

**Comment by 524388475** [comment]
![Screenshot_20220118-055625](https://user-images.githubusercontent.com/72139364/149882861-c746e3ca-d60e-46b1-91df-c04bcb6a2b45.png)

**Comment by MistEO** [comment]
[v2.8.0](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.8.0) 尝试修复了一下_(:з」∠)_

**Comment by MistEO** [comment]
[新版本] (https://github.com/MistEO/MeoAssistantArknights/releases) 版本已修复，请体验~
