### ISSUE TITLE
[2.7.9]运行直接闪退，无log

### ISSUE THREAD

**Issue by Jie-Qiao** [MistEO/MeoAssistantArknights#121]
重新下载打开也不行

**Comment by maidangdang1** [comment]
我也是o(TヘTo)
观测到貌似是检测到更新就会闪退，昨晚检测到2.7.8更新之后就一直闪退，手动更新才能解决
附两次闪退时间段：[2022-01-19 01:51:40.524] ~ [2022-01-19 01:58:26.357]
[2022-01-19 12:37:06.622] ~ log末尾
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7894137/asst.log)

**Comment by guojunyu196** [comment]
我也是，使用下载的替换文件替换后，依然打开闪退，无log

**Comment by MistEO** [comment]
不好意思，`v2.7.9` 的包上传的好像有点问题，正在重新上传，请稍等_(:з」∠)_

**Comment by MistEO** [comment]
已重新打包上传

**Comment by MistEO** [comment]
> 我也是o(TヘTo) 观测到貌似是检测到更新就会闪退，昨晚检测到2.7.8更新之后就一直闪退，手动更新才能解决 附两次闪退时间段：[2022-01-19 01:51:40.524] ~ [2022-01-19 01:58:26.357] [2022-01-19 12:37:06.622] ~ log末尾 [asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7894137/asst.log)

- v2.7.9 崩溃是之前编译的包有问题，已重新编译上传
- 每次检测到更新就会崩溃，好像是个 bug，正在排查修复中

**Comment by MistEO** [comment]
[v2.8.0](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.8.0) 已修复检测到更新后的崩溃问题_(:з」∠)_
