### ISSUE TITLE
公开招募 时间设置错误

### ISSUE THREAD

**Issue by evilcatshare** [MistEO/MeoAssistantArknights#125]
貌似是 点进去 操作时候 有些延迟 没有选好时间
能否增加 一个 设置点击延迟 或 确认招募前 检查一下时间/tag是否正确
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7919453/asst.log)

**Comment by MistEO** [comment]
[v2.9.6] (https://github.com/MistEO/MeoAssistantArknights/releases) 版本已修复，请体验~
