### ISSUE TITLE
公招显示识别错误

### ISSUE THREAD

**Issue by NULLlnull** [MistEO/MeoAssistantArknights#126]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7924803/asst.log)
![image](https://user-images.githubusercontent.com/35243163/150767124-c4fe68c3-1593-4957-8916-bd01cfac3fe4.png)

模拟器使用的是雷电模拟器 v4.0.67 (64bit)，一开始分辨率使用的是3440 x 1440，后来使用1080P也依旧无效，游戏里公招时间设置到了9小时。访问好友功能有用，而且识别到我今天访问过了就退出去了

Android Debug Bridge version 1.0.41
Version 31.0.3-7562133
Installed as C:\platform-tools\adb.exe

adb我在环境变量里设置好了。软件里就没有单独设置了

**Comment by MistEO** [comment]
> 目前仅对 16:9 分辨率支持较好，其他分辨率勉强可用，但可能会有奇奇怪怪的问题，正在进一步适配中_(:з」∠)_

**Comment by NULLlnull** [comment]
重新下载了个蓝叠，现在1080P默认分辨率可用，换成3440 x 1440先闪退了一次，然后也和雷电一样识别错误了。但雷电1080P也会识别错误。另，大佬能加一个三星tag公招时间8小时吗，我自己玩的时候四星tag我也是8小时的，但这个可能每个人喜好不一样，三星公招8小时大家应该是没有争议的吧？议的吧？
