### ISSUE TITLE
自动公招在使用联络次数后没有重新设置招募时间

### ISSUE THREAD

**Issue by Loooooory** [MistEO/MeoAssistantArknights#127]
![图片](https://user-images.githubusercontent.com/44219314/150989341-806c5db4-c826-40f3-837c-dec7b241f5ad.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7934059/asst.log)
招募第一个的时候先调整时间到9小时之后才使用联络次数进行的tag刷新，刷新之后招募时间就变回1小时了orz。对于招募三星来说可能问题不大，但是可能存在刷新出四星干员tag并自动确认四星五星，但是没有设置9小时的情况（？）

**Comment by Loooooory** [comment]
https://drive.google.com/file/d/1-ixWc0UHP6JgR7Fse_x3IcMf0fxRliwg/view?usp=sharing
复现

**Comment by MistEO** [comment]
[v2.9.6] (https://github.com/MistEO/MeoAssistantArknights/releases) 版本已修复，请体验~
