### ISSUE TITLE
如果 v2.7.9 版本一启动就闪退，请手动重新下载使用 v2.8.0 版本~

### ISSUE THREAD

**Issue by MistEO** [MistEO/MeoAssistantArknights#128]
v2.7.9 的自动更新功能出了点 bug, 本来是检查到新版本就自动更新，结果变成了检查到新版本就闪退 or 报错了2333

麻烦大家手动 [下载](https://github.com/MistEO/MeoAssistantArknights/releases) 吧，新版本以后应该不会有这个问题了_(:з」∠)_

**Comment by Loooooory** [comment]
正好在解决docker和模拟器一个要开hyperV，一个要关hyperV的问题，还以为是环境出了问题重新配置了一遍环境23333，最后才排除到助手本身
