### ISSUE TITLE
谜之闪退

### ISSUE THREAD

**Issue by cglcv** [MistEO/MeoAssistantArknights#130]
2.8.0版本，蓝叠模拟器5.5，刷将进酒IW-8结算界面识别时不定期闪退（未闪退的情况提示企鹅物流数据上传失败）
bluesticks.conf目录已写，将config,json中的[Adb]替换成了adb，使用系统环境变量中配置好的adb
删除以上自定义内容后未发现闪退现象
adb版本：
Android Debug Bridge version 1.0.41
Version 31.0.3-7562133
最后一次闪退时的log：
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7938655/asst.log)
PS：使用源代码生成并在vs调试器环境下运行，即使自定义adb也未发生任何闪退，但也不出现企鹅物流上传失败提示

**Comment by cglcv** [comment]
补个一直传不上来的截图：
![Screenshot_2022 01 26_10 25 55 053](https://user-images.githubusercontent.com/35825310/151098352-d5f19496-d0de-452f-84e8-6c62860be0ad.png)

**Comment by MistEO** [comment]
资源文件好像不对，重新解压下看看。软件打开后有提示资源已自动更新么？

**Comment by cglcv** [comment]
> 资源文件好像不对，重新解压下看看。软件打开后有提示资源已自动更新么？

有提示，我重新解压下试试

**Comment by MistEO** [comment]
> > 资源文件好像不对，重新解压下看看。软件打开后有提示资源已自动更新么？
> 
> 有提示，我重新解压下试试

不应该有提示，v2.8.0 里的资源已经是最新的了。我昨天调试的时候也遇到了一次提示更新，但没当回事，后来也没复现了_(:з」∠)_回头我再来研究下咋回事

**Comment by cglcv** [comment]
重新解压后没有提示，也没有出现过任何闪退现象了
可能真的是更新时资源出问题了

**Comment by MistEO** [comment]
那我关了哦_(:з」∠)_
