### ISSUE TITLE
重复访问基建的同一房间

### ISSUE THREAD

**Issue by zlqd123** [MistEO/MeoAssistantArknights#132]
![6X2D94J1E%AXE(TW9YHZA$I](https://user-images.githubusercontent.com/32678715/151183237-83635021-52d8-4afc-8cec-c86d2127d6d7.png)

[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7942610/asst.log)
2022-01-26 22时附近

**Comment by guojunyu196** [comment]
同，我是在制造站和控制中枢

[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7943131/asst.log)

**Comment by MistEO** [comment]
好像办公室没有识别到有办公室技能的人，是没有干员么？

**Comment by MistEO** [comment]
> 同，我是在制造站和控制中枢
> 
> [asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7943131/asst.log)

你是逍遥模拟器吗，README忘记写了，逍遥和mumu一样，渲染方式很奇怪，经常会识别错，换个模拟器试试？

**Comment by zlqd123** [comment]
> 
场景是办公室，但是进驻界面全是贸易站技能干员优先。
这之前电脑卡了一会

**Comment by MistEO** [comment]
> > 
> 
> 场景是办公室，但是进驻界面全是贸易站技能干员优先。 这之前电脑卡了一会

那种这没有办法，识别不到技能就会重试，重试次数达到上限就会报错，当前重试次数是 20 次，之后可能会考虑把重试次数改小一点
