### ISSUE TITLE
能否添加启动参数，运行时直接开始任务

### ISSUE THREAD

**Issue by miku1958** [MistEO/MeoAssistantArknights#133]
我希望写个开机脚本，自动执行程序然后自动关机

脚本里准备好模拟器后直接MeoAsstGui.exe -linkstart之类的，打开后就直接开始任务了

**Comment by MistEO** [comment]
CLI 版本正在开发中，当前可以参考使用 [Python 接口](https://github.com/MistEO/MeoAssistantArknights/wiki/Python-%E6%8E%A5%E5%8F%A3)

**Comment by miku1958** [comment]
Ok thanks
