### ISSUE TITLE
希望能添加对外国服的支持

### ISSUE THREAD

**Issue by HTLXMC** [MistEO/MeoAssistantArknights#134]
希望能添加对外国服的支持

**Comment by MistEO** [comment]
目前美服支持少部分功能，[参考这里](https://github.com/MistEO/MeoAssistantArknights/blob/master/docs/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md#%E6%88%91%E6%98%AF%E5%9B%BD%E9%99%85%E6%9C%8D%E7%8E%A9%E5%AE%B6%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E4%B9%88)，近期可能会完善更多的功能。

日服、韩服等，短期内不会被支持
