### ISSUE TITLE
建议在肉鸽加入在第一层商店存源石锭选项

### ISSUE THREAD

**Issue by Dumpling-Dragon** [MistEO/MeoAssistantArknights#136]
建议在肉鸽加入在第一层商店存源石锭选项，以便刷源石锭（毕竟现在蜡烛大多满了）

**Comment by MistEO** [comment]
可以的，现在就是支持的，接口已经写好了，但是因为图形界面还没写，所以没办法选。会跟着图形界面一起上线

**Comment by Mashiro173** [comment]
> 可以的，现在就是支持的，接口已经写好了，但是因为图形界面还没写，所以没办法选。会跟着图形界面一起上线

2.9.2开启只刷源石锭只会到第一层停下，但不会手动往里存源石锭

**Comment by MistEO** [comment]
已修复，请尝试 v2.9.4 新版本~

**Comment by Dumpling-Dragon** [comment]
十分感谢，祝作者新年快乐ヾ(◍°∇°◍)ﾉﾞ
