### ISSUE TITLE
基建换班死循环

### ISSUE THREAD

**Issue by miku1958** [MistEO/MeoAssistantArknights#138]
选中了清流和槐琥，然后无视了砾小姐，之后就一直来回滚动屏幕了

![MuMu20220127202419](https://user-images.githubusercontent.com/24806909/151358303-85d3ea42-3c52-4b52-b08f-cbe295ceb293.png)

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7950350/asst.log)

**Comment by MistEO** [comment]
不会死循环的，是识别偶尔不准，会重试，请耐心等一小会（
