### ISSUE TITLE
蓝叠模拟器，连接上模拟器之后可识别到界面，但是操作不了

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#139]
不知道啥情况，反正模拟器全程没动，gui这边一直在Mg0循环
![8ZP B )NEQ (FP 6X$7M4JH](https://user-images.githubusercontent.com/76220347/151373857-8966ac03-3f58-4a6e-96a6-c389d2905faa.png)
![BS_PIC_2022-01-27-21-59-55](https://user-images.githubusercontent.com/76220347/151373873-44e00de3-0c7b-43eb-8820-f63e29820cc3.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7951044/asst.log)

Thanks♪(･ω･)ﾉ

**Comment by MistEO** [comment]
蓝叠的 adb 炸了，模拟器自身的问题，没啥好办法。如果经常这样的话可以考虑换个模拟器

**Comment by MistEO** [comment]
解决了的话，ISSUE 我关掉了哦(*´▽｀)ノノ
