### ISSUE TITLE
代理刷活动本bug，第一次点进去会自动暂停，后续会有无法自动作战的情况发生

### ISSUE THREAD

**Issue by LuvEven** [MistEO/MeoAssistantArknights#140]
模拟器：夜神模拟器
分辨率：1600*900
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7951870/asst.log)

**Comment by LuvEven** [comment]
补充一下，界面的日志是卡在当次的已开始行动，作战结束后没有获取到掉落统计

**Comment by MistEO** [comment]
[v2.9.6] (https://github.com/MistEO/MeoAssistantArknights/releases) 版本已修复，请体验~

**Comment by LuvEven** [comment]
> [v2.9.6] ( https://github.com/MistEO/MeoAssistantArknights/releases ) 版本已修复，请体验~

偶尔还是有这个问题，会是电脑内存不够掉帧导致的吗？

**Comment by LuvEven** [comment]
> [v2.9.6] ( https://github.com/MistEO/MeoAssistantArknights/releases ) 版本已修复，请体验~

活动副本iw-6这张图，挂理智方式：**上次关卡**
