### ISSUE TITLE
rouge有初始收藏品会卡住不进入

### ISSUE THREAD

**Issue by Mashiro173** [MistEO/MeoAssistantArknights#141]
模拟器是蓝叠国际版 另外打到第三层的boss关也卡住过一次
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7953937/asst.log)

**Comment by Mashiro173** [comment]
补充下目前看到会卡住的关卡有鸭爵的特殊关卡

**Comment by Mashiro173** [comment]
不好意思原来初始收藏品是因为我手抖点了观光模式_(:з」∠)_

**Comment by MistEO** [comment]
- 不支持观光模式
- 鸭爵卡住的问题，[v2.9.3](https://github.com/MistEO/MeoAssistantArknights/releases) 最新版本已修复~
