### ISSUE TITLE
自动肉鸽存在进入商店后不存源石锭的BUG

### ISSUE THREAD

**Issue by CurTa1nzZ** [MistEO/MeoAssistantArknights#142]
RT, 使用雷电模拟器其他功能目前一切正常，但是新推出的自动刷源石锭的功能存在只进入商店但是不往投资系统内存源石锭的BUG, 本来以为是偶然状况但是连续两次都是这样...
脚本方面只勾选了自动肉鸽，设置里面勾选了“仅刷源石锭投资”。
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7955114/asst.log)

**Comment by u81668899** [comment]
雷电模拟器，同上……

**Comment by MistEO** [comment]
[v2.9.3](https://github.com/MistEO/MeoAssistantArknights/releases) 最新版本已修复~
