### ISSUE TITLE
图像错误

### ISSUE THREAD

**Issue by xiaoweiXX** [MistEO/MeoAssistantArknights#143]
目前我还没有用这个软件挂方舟，但是遇到了一些图形化问题。以下是具体描述：
1.按钮在鼠标扫过之后会消失，之后只有在鼠标扫到时才能显示
![屏幕截图 2022-01-28 095817](https://user-images.githubusercontent.com/92417243/151474312-be1ff724-206f-4cb6-b55c-6814340a7b67.jpg)
2.有时复选框的显示也会抽风
![屏幕截图 2022-01-28 100403](https://user-images.githubusercontent.com/92417243/151474440-17ec418a-7ebb-4965-bf61-8fc210934278.jpg)
这是log
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7955150/asst.log)

**Comment by Mashiro173** [comment]
这个问题我也有发生..不过不怎么影响使用就没去管

**Comment by MistEO** [comment]
这个问题可能和运行库、电脑的渲染方式等有关，比较无解_(:з」∠)_

过一段时间新框架的界面会上线，到时候看看还有没有这种问题吧，issue 我先关掉了orz
