### ISSUE TITLE
肉鸽卡住

### ISSUE THREAD

**Issue by xiaoweiXX** [MistEO/MeoAssistantArknights#144]
使用的模拟器是雷电模拟器。
具体问题为肉鸽打到第一层时遭遇鸭爵，选择战斗选项后卡在进入战斗页面一动不动，下面是截图和log
![屏幕截图 2022-01-28 101958](https://user-images.githubusercontent.com/92417243/151476131-9dc01f70-fdaf-4112-9003-566d6d0faffd.jpg)
![屏幕截图 2022-01-28 102020](https://user-images.githubusercontent.com/92417243/151476141-2a1270bc-bd32-4dab-ab53-16c474d2ac63.jpg)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7955232/asst.log)

**Comment by xiaoweiXX** [comment]
并且肉鸽的智能程度也有问题，有时候干员下的位置不太好，选干员的时候甚至选了个很差的！结束战斗之后选干员，我梅尔基本上没练过，同时也有其他的一些辅助干员，但是还是选了梅尔

**Comment by u81668899** [comment]
同雷电模拟器，同样遇到识别关卡商店时卡住问题，提示关卡为不期而遇

**Comment by mslxl** [comment]
蓝叠 1920x1080 分辨率可稳定复现（可能没写这个逻辑？）

这些地方也会卡住：

![Screenshot_2022 01 28_11 15 20 088](https://user-images.githubusercontent.com/11132880/151482521-5c364399-d176-4a0c-93d9-782074bbcb6e.png)

![Screenshot_2022 01 28_12 03 43 249](https://user-images.githubusercontent.com/11132880/151485424-96585353-fc70-4574-9c61-e57788638ff2.png)

**Comment by guojunyu196** [comment]
在此界面卡住
![BS_PIC_2022-01-28-12-15-54](https://user-images.githubusercontent.com/76220347/151486442-438547a6-0301-428d-84b1-ce362551dd25.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7955621/asst.log)

**Comment by xiaoweiXX** [comment]
不只是鸭爵，貌似所有的可重复的不期而遇（比如骗钱的老太太）都只会执行一遍，然后卡住

**Comment by guojunyu196** [comment]
在此界面卡住
![BS_PIC_2022-01-28-13-13-50](https://user-images.githubusercontent.com/76220347/151492330-fcb3ef06-8731-48c9-be98-857bfec7ef2c.png)

![4af52f73da77e892dfbe9171b2d7a51](https://user-images.githubusercontent.com/76220347/151492389-be98aecd-0a59-4199-a03e-93429a525f9d.png)

[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7955934/asst.log)

**Comment by MistEO** [comment]
[v2.9.3](https://github.com/MistEO/MeoAssistantArknights/releases) 最新版本已修复~
