### ISSUE TITLE
rouglike 可不可以选择优先选择练度高的，再选择适配度高的

### ISSUE THREAD

**Issue by jiang2018113436** [MistEO/MeoAssistantArknights#145]
每次都是选煌和幽灵鲨，但是这两个都没练

**Comment by MistEO** [comment]
可以手动修改 `resource/task.json` 文件中 `"Roguelike1ChooseOper"` 字段，目前还没来得及做到界面上

**Comment by MistEO** [comment]
统一至 https://github.com/MistEO/MeoAssistantArknights/issues/167 跟进，相关 issue 先关啦~
