### ISSUE TITLE
肉鸽自动的一些问题

### ISSUE THREAD

**Issue by w1017064903** [MistEO/MeoAssistantArknights#146]
熊线的不期而遇无响应；
前几次选银灰的时，进作战后，程序闪退（我电脑问题？）；
下干员有点晚，已经漏了银灰才落地；
![未响应](https://user-images.githubusercontent.com/98521231/151530516-d5e96442-a441-4e57-b186-fab58b520df1.png)

模拟器：雷电模拟器
PS：选棘刺为什么精二不选三技能（doge）

**Comment by w1017064903** [comment]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7957962/asst.log)

**Comment by MistEO** [comment]
[v2.9.3](https://github.com/MistEO/MeoAssistantArknights/releases) 最新版本已修复~
