### ISSUE TITLE
识别时闪退

### ISSUE THREAD

**Issue by 1169876030** [MistEO/MeoAssistantArknights#148]
雷电模拟器
公招识别时到正在识别。。。后过几秒就闪退

[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7958661/asst.log)

**Comment by MistEO** [comment]
模拟器的问题，有一条需要的 adb 命令不支持。不过按理说雷电应该没这个问题，升级下版本或者换个模拟器试试

**Comment by 1169876030** [comment]
感谢，换了个模拟器问题已解决
