### ISSUE TITLE
肉鸽进入熊线时的窗口没有关闭

### ISSUE THREAD

**Issue by w1017064903** [MistEO/MeoAssistantArknights#149]
![QQ截图20220128205500](https://user-images.githubusercontent.com/98521231/151550657-6c98ca3f-05e1-464a-b798-7ce55ba9f3ff.png)

**Comment by MistEO** [comment]
麻烦附上日志谢谢

**Comment by w1017064903** [comment]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7960116/asst.log)

**Comment by MistEO** [comment]
已修复，请尝试 v2.9.4 新版本~
