### ISSUE TITLE
将肉鸽开局自动选的银灰改成山，并自动开启山的二技能

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#150]
山的二技能有自回血能力，且攻击频率高，使打关失败率更小

**Comment by xiaoweiXX** [comment]
类似的问题还有很多，比如满练的煌默认一技能，就是不换2技能；再比如头一张图（第一次肉鸽好像叫驯兽师来着？）第二个放梓兰，放下去之后医疗费够了之后不放医疗，非得等祭坛喷两下把梓兰喷死再放医疗。就在刚刚，这有限的人工智能又做出了非常傻的操作，初始那几张图有4个狙击手和几个幽灵那张图，开场不放煌，反倒是放狙击和医疗什么的，漏虫子漏到关卡失败

**Comment by u81668899** [comment]
家门常打开是经常有的

**Comment by MistEO** [comment]
> 类似的问题还有很多，比如满练的煌默认一技能，就是不换2技能；再比如头一张图（第一次肉鸽好像叫驯兽师来着？）第二个放梓兰，放下去之后医疗费够了之后不放医疗，非得等祭坛喷两下把梓兰喷死再放医疗。就在刚刚，这有限的人工智能又做出了非常傻的操作，初始那几张图有4个狙击手和几个幽灵那张图，开场不放煌，反倒是放狙击和医疗什么的，漏虫子漏到关卡失败


因为不是所有人都有某个干员，策略需要尽可能支持所有可能出现的干员，而不是针对每一个干员单独写一套策略，那样工程量太大了

MAA 追求的是尽可能稳定的让更多的人用上自动肉鸽，反正是挂机让脚本打，又不用你费心，只要不卡住，什么都好说（虽然现在仍有许多卡住的问题，但这都是将来会优化和修复的），所以 MAA 支持了尽可能多的模拟器，并且对分辨率、dpi 等都几乎没有要求

如果你是全干员/高练度，想追求更高效率的肉鸽，请尝试隔壁 [明日再肝](https://github.com/Lancarus/Liver-Arknights-Tomorrow) 或 [明日方舟速通](https://github.com/tkkcc/arknights)

**Comment by MistEO** [comment]
统一至 https://github.com/MistEO/MeoAssistantArknights/issues/167 跟进，相关 issue 先关啦~
