### ISSUE TITLE
肉鸽还是会卡住

### ISSUE THREAD

**Issue by xiaoweiXX** [MistEO/MeoAssistantArknights#152]
雷电模拟器
打到第3层底的BOSS会卡住，重启开始之后会直接放弃本次探索。

**Comment by MistEO** [comment]
麻烦附上日志谢谢

**Comment by xiaoweiXX** [comment]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7959720/asst.log)
我有点怀疑是不是设计的就是如此

**Comment by MistEO** [comment]
[v2.9.6] (https://github.com/MistEO/MeoAssistantArknights/releases) 版本已修复，请体验~
