### ISSUE TITLE
蓝叠国际版进入作战会卡住

### ISSUE THREAD

**Issue by paradooogs** [MistEO/MeoAssistantArknights#153]
![image](https://user-images.githubusercontent.com/98599025/151566196-fb0fbf53-fcd8-4e24-837a-d1e0799395ba.png)
如图

**Comment by paradooogs** [comment]
补充一下，大锁事件还是会卡住

**Comment by MistEO** [comment]
麻烦发下日志吧~

**Comment by MistEO** [comment]
[v2.9.6] (https://github.com/MistEO/MeoAssistantArknights/releases) 版本已修复，请体验~
