### ISSUE TITLE
投资商店不存石头直接结束

### ISSUE THREAD

**Issue by yu-echo** [MistEO/MeoAssistantArknights#154]
到这个界面就直接退了，不存钱qaq
![MuMu20220128233952](https://user-images.githubusercontent.com/66340881/151577925-361be713-e356-425a-a7c9-d780f1781432.png)

具体日志如下
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7959953/asst.log)

**Comment by MistEO** [comment]
已修复，请尝试 v2.9.4 新版本~
