### ISSUE TITLE
肉鸽大锁

### ISSUE THREAD

**Issue by 1553767977** [MistEO/MeoAssistantArknights#155]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7960711/asst.log)
肉鸽在不期而遇里面捡到玩偶转大锁线的时候会跳出这个界面
模拟器没截到我去b站找的
![image](https://user-images.githubusercontent.com/39228172/151595269-3587759f-82a9-4db4-86ce-19fbb04442d5.png)
然后程序就在这个界面完全不动了
手动点掉这个界面之后恢复正常
日志里面第一把就是了
为什么有那么多次已停止的log
因为我耳机压到右边的enter了。。。。。

**Comment by MistEO** [comment]
v2.9.4 版本已经修复了，更新下试试吧~
