### ISSUE TITLE
rouge鸭爵关卡不会下干员

### ISSUE THREAD

**Issue by Mashiro173** [MistEO/MeoAssistantArknights#156]
蓝蝶国际版
rt 鸭爵关卡不会下干员导致一关漏掉所有怪
另外还有一些问题
1.干员下在无效位置 无效朝向 比如芙蓉面壁朝向没有己方干员的地方导致奶不到人 煌朝墙里只能打到自己所在格子的怪
2.有2个蓝点的地图会只防守1个点大量漏怪
另附一些小建议
1.希望能增加一些干员的选取，比如山 棘刺等泛用性高的干员，没有希望的时候可以在白板干员和克洛丝之间选择克洛丝
2.希望能参考一些做攻略的up所做的泛用性攻略来进行干员部署，这样通过率应该也会高一些
3.希望能将只刷源石锭拆分为 有投资商店时投资源石锭至上限 和 只周回第一层，因为只周回第一层来刷取源石锭较大概率因为商店不能投资 效率非常低（挂了几轮只刷到3个）
感谢_(:з」∠)_
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7961245/asst.log)

**Comment by MistEO** [comment]
- 鸭爵问题：好像没怎么测过，会尝试去修复下
- 下干员：目前的策略不是针对每一关单独做的，而是一个通用的策略。因为每个月地图都可能更新，全都单独做太肝了 orz, 这个通用策略可能会去优化，但是没法进行所谓的抄作业
- 干员的自定义选择：当前其实就是支持的，只不过界面上没有开放出来。可以先尝试手动修改 `resource/task.json` 文件中 `"Roguelike1ChooseOper"` 字段
- 增加投资源石锭选项：好主意！之后的版本就加上！

**Comment by Mashiro173** [comment]
用QQ截图好像是正常的 我试了用系统自带重新截
![image](https://user-images.githubusercontent.com/98558933/151616210-27cec51d-9f06-442c-ab48-05467d1cab48.png)

**Comment by MistEO** [comment]
这种通常是系统渲染问题，没啥好办法_(:з」∠)_可以重装下运行库看看

不过新 UI 已经在做了，估计没用这个问题了

**Comment by Mashiro173** [comment]
感谢大佬回复 有什么新bug我及时来报错

**Comment by MistEO** [comment]
v2.9.5 已修复鸭爵卡住的问题，请体验~
