### ISSUE TITLE
肉鸽关卡后战利品选择BUG

### ISSUE THREAD

**Issue by CurTa1nzZ** [MistEO/MeoAssistantArknights#157]
在作战关卡结束后有概率遇到的选择剧目的部分，存在选择完剧目之后卡住的情况。
![image](https://user-images.githubusercontent.com/44784817/151625806-5bfa04bf-c325-443b-91ae-703bd4d27315.png)
附log:
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7961992/asst.log)

**Comment by MistEO** [comment]
[v2.9.6] (https://github.com/MistEO/MeoAssistantArknights/releases) 版本已修复，请体验~
