### ISSUE TITLE
基建换班卡住

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#159]
如图
![uTools_1643414549756](https://user-images.githubusercontent.com/76220347/151639879-6c9723c4-46bb-427e-ab02-c45628d0812e.png)
![uTools_1643414574332](https://user-images.githubusercontent.com/76220347/151639881-9f973904-9f0e-4406-9edb-083d7f67ff94.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7962629/asst.log)

Thanks♪(･ω･)ﾉ

**Comment by MistEO** [comment]
这个问题 v2.9.3 已经修复啦，请体验新版本~
