### ISSUE TITLE
2.8.0有线索满时不收取自己线索的bug

### ISSUE THREAD

**Issue by VicetoneMusic** [MistEO/MeoAssistantArknights#160]
很抱歉忘记截图了……但我是看着它的，
就是进入会客室，先领自己的线索，然后线索满了领不了，就自动送了几个线索。
之后就领了别人给的线索，但就是没有领自己的然后就退出会客室了。
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7962786/asst.log)

up主推荐的bluestack模拟器

**Comment by MistEO** [comment]
[v2.9.6] (https://github.com/MistEO/MeoAssistantArknights/releases) 版本已修复，请体验~
