### ISSUE TITLE
暴殄天物（喝酒）的不期而遇识别出错卡住

### ISSUE THREAD

**Issue by Melanotis** [MistEO/MeoAssistantArknights#162]
![图片](https://user-images.githubusercontent.com/70083631/151646249-15e7b2bb-8681-4d8b-bdef-e2ad531fc18a.png)
![图片](https://user-images.githubusercontent.com/70083631/151646252-6e9132e8-95f7-47d7-ae12-b282252f2316.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7962916/asst.log)
用的是mumu，不知道模拟器的影响大不大，如果有问题就换个模拟器了_(:з」∠)_
_(:з」∠)_

**Comment by MistEO** [comment]
居然还有四个选项的时候 orz

“确定这么做“ 下面那个 √ 被挡住了一般，没识别到

下个版本修复（

**Comment by MistEO** [comment]
[v2.9.6] (https://github.com/MistEO/MeoAssistantArknights/releases) 版本已修复，请体验~
