### ISSUE TITLE
选完人之后就不动了（有时候选完辅助和医疗也会不动）

### ISSUE THREAD

**Issue by w1017064903** [MistEO/MeoAssistantArknights#163]
![QQ截图20220129121758](https://user-images.githubusercontent.com/98521231/151648465-c981217f-2084-435e-ac1a-2416c306965e.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7963020/asst.log)
雷电模拟器

**Comment by john180** [comment]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7963038/asst.log)
夜神也有同样的问题  版本是v2.9.5

**Comment by MistEO** [comment]
[v2.9.6] (https://github.com/MistEO/MeoAssistantArknights/releases) 版本已修复，请体验~
