### ISSUE TITLE
肉鸽第一层刷原石锭遇到剧目会卡住

### ISSUE THREAD

**Issue by e0kt** [MistEO/MeoAssistantArknights#164]
蓝叠模拟器国际版 v2.95
![TVL)8 )CL$7$FD$@UW(@X3K](https://user-images.githubusercontent.com/23226657/151649527-d67ef7e7-17f6-4b5f-9f41-675021885bef.png)

[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7963066/asst.log)

**Comment by MistEO** [comment]
[v2.9.6] (https://github.com/MistEO/MeoAssistantArknights/releases) 版本已修复，请体验~
