### ISSUE TITLE
信用商店购买优化建议

### ISSUE THREAD

**Issue by lhhxxxxx** [MistEO/MeoAssistantArknights#165]
1. 不买加急许可
2. 优先购买打折商品（从左上角开始买）

**Comment by MistEO** [comment]
请参考 [详细介绍 - 信用商店随缘买](https://github.com/MistEO/MeoAssistantArknights/blob/master/docs/%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.md#%E4%BF%A1%E7%94%A8%E5%95%86%E5%BA%97%E9%9A%8F%E7%BC%98%E4%B9%B0)

>  ## 信用商店随缘买
> 
> 从左到右依次买，但不会买 `碳` 和 `家具零件` 。有需要的同学可自行修改 `resource/tasks.json` 中 `CreditShop-NotToBuy` - `text` 字段，自定义不买的物品。后续版本会尝试开放界面选项
