### ISSUE TITLE
肉鸽选人建议

### ISSUE THREAD

**Issue by w1017064903** [MistEO/MeoAssistantArknights#166]
虽然有点过分，但是看见选了一个完全没练过的干员有点高血压（比如白金我就没练，我练蓝毒了。。。）

**Comment by guojunyu196** [comment]
可以手动修改resource/task.json文件中"Roguelike1ChooseOper"的位置
同#145

**Comment by MistEO** [comment]
可以手动修改 `resource/task.json` 文件中 `"Roguelike1ChooseOper"` 字段，目前还没来得及做到界面上

**Comment by MistEO** [comment]
统一至 https://github.com/MistEO/MeoAssistantArknights/issues/167 跟进，相关 issue 先关啦~

**Comment by Ga1en70** [comment]
> 可以手动修改resource/task.json文件中"Roguelike1ChooseOper"的位置 同#145

怎么修改带什么技能啊
