### ISSUE TITLE
2.9.6 肉鸽招人时卡住

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#169]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7964044/asst.log)
![BS_PIC_2022-01-29-23-57-32](https://user-images.githubusercontent.com/76220347/151667766-ccff4686-bac3-4717-839c-a15f48bb0325.png)
已经不是第一次了，更新之后这是第三次，前两次没截到

**Comment by MistEO** [comment]
你电脑好卡啊 QAQ 一般应该不会出这个bug 的 orz

已经修复了，急的话可以照着 [这个提交](https://github.com/MistEO/MeoAssistantArknights/commit/29cee57e231b8d5f912f9dc6244fd47b85f021e7) 修改一下配置文件_(:з」∠)_ 不记得话等等发版

**Comment by MistEO** [comment]
v2.9.7 修复啦~ 请更新体验
