### ISSUE TITLE
2.9.7  肉鸽投资异常

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#173]
投资不会停下，直到手动停止
![BS_PIC_2022-01-30-08-45-57](https://user-images.githubusercontent.com/76220347/151682549-3d49b74b-a33c-49a4-b48c-7aba4ca461c8.png)
![$)6 ((A%7FUU{ZX(%YU%UIW](https://user-images.githubusercontent.com/76220347/151682552-c6e26458-50e9-40c7-8f90-eeeee72e418a.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7965073/asst.log)

**Comment by guojunyu196** [comment]
重试了一下，更离谱了_(:з」∠)_
![DQWK`)GIJ40`JSHFEK{C D7](https://user-images.githubusercontent.com/76220347/151683804-e1f38017-521c-4d14-ab8b-bfc737852fb2.png)

**Comment by MistEO** [comment]
是不是直接替换了老版本的 tasks.json, _(:з」∠)_

不行的，每个版本的这个文件都不一样，会有问题的

**Comment by guojunyu196** [comment]
啊这，好吧，谢谢
顺便问下gui.json可以替换吗，每次更新之后懒得再设置一遍了

**Comment by MistEO** [comment]
> 啊这，好吧，谢谢 顺便问下gui.json可以替换吗，每次更新之后懒得再设置一遍了

这个没啥问题~
