### ISSUE TITLE
2.9.6 第二层作战卡住了

### ISSUE THREAD

**Issue by maidangdang1** [MistEO/MeoAssistantArknights#174]
卡在这里不点进入了😭
![Screenshot_2022 01 30_10 51 51 339](https://user-images.githubusercontent.com/46847241/151684947-cdc31e38-7abe-4b83-8743-5dd1b7bf2e89.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7965218/asst.log)

**Comment by MistEO** [comment]
v2.9.8 已修复~
