### ISSUE TITLE
公招卡死

### ISSUE THREAD

**Issue by hjhjfhjhujhh** [MistEO/MeoAssistantArknights#177]
此bug稳定可复现；自动公招中，在出现四星tag、招聘许可用尽、有刷新机会的情况下（图一），它会选中tag，确认招募（当然不成功），日志会显示确认招募，然后就会点击刷新标签，弹出确认刷新界面（图二）后软件就会识别错误，并且游戏一直卡在此界面，导致之后的任务全部出错
因为bug可复现的关系，我清理了log文件，所以log里只有重新打开软件到任务全部完成的内容
![Z1G2SC2L~ L~W@S4$%{IM}T](https://user-images.githubusercontent.com/89215821/151701742-126d6228-e6e3-47d2-85f7-9c888fd4fe84.png)
![ST%GC6OV2680GW62D{_H8A3](https://user-images.githubusercontent.com/89215821/151701744-a6189a15-7a84-4506-8859-c59cce277c29.png)
![NM`I1{~PP~9$A3L)VMI 1)0](https://user-images.githubusercontent.com/89215821/151701745-78eacf64-4d84-49b3-98ee-96f874ae1027.png)
日志文件：
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7965977/asst.log)

**Comment by MouseWhite** [comment]
+1 望修复

**Comment by MistEO** [comment]
[v3.0.2](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v3.0.2) 已修复，请体验~
