### ISSUE TITLE
希望肉鸽刷源石锭存款能够支持简单（古堡观光）模式

### ISSUE THREAD

**Issue by HJTY0** [MistEO/MeoAssistantArknights#178]
简单模式下关卡通过率更高，而且刷存款效率是一样的。
简单模式下第一个界面是获取藏品，当前版本的脚本会卡住。

**Comment by MistEO** [comment]
感谢建议，[v3.0.1](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v3.0.1) 版本已经支持啦~
