### ISSUE TITLE
测试版本更新错误？也许可以加个进度条之类的？

### ISSUE THREAD

**Issue by AlexYangCong** [MistEO/MeoAssistantArknights#180]
测试版更新系统弹窗提示后台下载，然后就没消息了，挂了整整一小时，还是没结果没啥反应版本号也没变，就手动跳转页面下载秒下，再手动替换了。它是应该下载完重启软件咩？大佬做个更新进度条呗？只有一个后台下载文本比较迷茫啊。

**Comment by MistEO** [comment]
有 bug，不知道咋修 orz（gui 我不太会搞，现在的是糊出来的

有大佬在帮忙做全新的 gui 了，我摆了（

**Comment by AlexYangCong** [comment]
好嘞，有个更新失败的反馈就行hhhh（有看到提示啦），新年快乐嗷
