### ISSUE TITLE
肉鸽选人页面稳定闪退

### ISSUE THREAD

**Issue by breathiness** [MistEO/MeoAssistantArknights#182]
![图片](https://user-images.githubusercontent.com/11361630/151801806-95064e7d-64ad-403d-b7f0-aecc898ffbf6.png)

[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7971004/asst.log)

**Comment by breathiness** [comment]
昨天第一次打开软件时是可以正常刷的，第二天再开就不行了

**Comment by MistEO** [comment]
重启 & 重新下载试试 _(:з」∠)_

**Comment by breathiness** [comment]
> 重启 & 重新下载试试 _(:з」∠)_

用最新的 3.0 版本重新安装试了试，最开始刷的几轮没问题。然后就跳出错误，之后就跟之前一样了。在选人页面会炸。
下面是炸的截图以及 log 文件。（炸的时候还把我其他应用也一起炸了，后台的应用全给退了）
![Clip_20220201_133104](https://user-images.githubusercontent.com/11361630/151918386-8613503e-05f7-4862-b918-fe8cfff31be5.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7976150/asst.log)

**Comment by MistEO** [comment]
[v3.0.2](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v3.0.2) 尝试修复了一下，不知道有没有效果，麻烦再进一步反馈下_(:з」∠)_

**Comment by breathiness** [comment]
> [v3.0.2](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v3.0.2) 尝试修复了一下，不知道有没有效果，麻烦再进一步反馈下_(:з」∠)_

今晚试了一下，似乎正常了。
