### ISSUE TITLE
程序自动退出

### ISSUE THREAD

**Issue by HaneRo** [MistEO/MeoAssistantArknights#183]
使用蓝叠模拟器（5.5.100.1040N64），出现错误时执行的操作是基建换班，屏幕黑屏，程序自动退出
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7975253/asst.log)

**Comment by james2002chen** [comment]
刷理智的时候也会出现这样的问题，夜神模拟器
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7975906/asst.log)

**Comment by MistEO** [comment]
v3.0.4 再次尝试修复了一下，这次应该可以了（）

**Comment by MistEO** [comment]
v3.0.5 再试着修复了一下，康康有没有效果 QAQ
