### ISSUE TITLE
希望可以优化下自动下载更新

### ISSUE THREAD

**Issue by Puqns67** [MistEO/MeoAssistantArknights#184]
由于国内的网络原因，下载来自github的文件常常无法正常下载，所以自动更新日常卡死，最后还是要手动上github下，所以希望能关闭自动下载更新，弹更新说明没啥问题。

设置中有选项："检查测试版本更新"，不启用时还是会检测到 github 上的 Pre-release，并自动下载，是不是有点不太合理

顺带说一下，启动下载后aria2进程不能在关闭Gui后自动关闭么（做成子进程），aria2能支持断点续传的啊

顺带再说一下，只打开Gui啥也不做，占~200MB内存，停止任务后是不是应该释放内存呢，这还是C++程序是不是有点太离谱了..建议优化一下吧

**Comment by MistEO** [comment]
- 界面是C#糊出来的，自动更新也是在界面上做的，我不会C#，现学现卖，这块的💩比较多。有大佬再帮忙重写新界面了
- 200M也主要是界面占的，单底层c++部分占用约50M，考虑到几百张模板图片，几个巨型json，还有ocr的模型加载。这个内存占用是比较合理的（

**Comment by Puqns67** [comment]
> * 界面是C#糊出来的，自动更新也是在界面上做的，我不会C#，现学现卖，这块的hankey比较多。有大佬再帮忙重写新界面了
> * 200M也主要是界面占的，单底层c++部分占用约50M，考虑到几百张模板图片，几个巨型json，还有ocr的模型加载。这个内存占用是比较合理的（

图片的话能做到开始阶段时加载对应阶段需求的图片，结束阶段时从内存del掉此阶段的图么，懂C++皮毛，感觉是可以实现的（我感觉能把这几百张图优化了关于内存优化这方面基本上就没啥问题了

**Comment by MistEO** [comment]
> > * 界面是C#糊出来的，自动更新也是在界面上做的，我不会C#，现学现卖，这块的hankey比较多。有大佬再帮忙重写新界面了
> > * 200M也主要是界面占的，单底层c++部分占用约50M，考虑到几百张模板图片，几个巨型json，还有ocr的模型加载。这个内存占用是比较合理的（
> 
> 图片的话能做到开始阶段时加载对应阶段需求的图片，结束阶段时从内存del掉此阶段的图么，懂C++皮毛，感觉是可以实现的（我感觉能把这几百张图优化了关于内存优化这方面基本上就没啥问题了

那就属于时间换空间了🤔

**Comment by Puqns67** [comment]
> > > * 界面是C#糊出来的，自动更新也是在界面上做的，我不会C#，现学现卖，这块的hankey比较多。有大佬再帮忙重写新界面了
> > > * 200M也主要是界面占的，单底层c++部分占用约50M，考虑到几百张模板图片，几个巨型json，还有ocr的模型加载。这个内存占用是比较合理的（
> > 
> > 
> > 图片的话能做到开始阶段时加载对应阶段需求的图片，结束阶段时从内存del掉此阶段的图么，懂C++皮毛，感觉是可以实现的（我感觉能把这几百张图优化了关于内存优化这方面基本上就没啥问题了
> 
> 那就属于时间换空间了🤔

我觉得是赚的，用到时再读取不应该更好么，都挤在启动程序时加载且不丢弃反而会拖慢启动速度，并且使内存占用变大
