### ISSUE TITLE
一些小问题（识别&卡关）

### ISSUE THREAD

**Issue by MeadalFlute** [MistEO/MeoAssistantArknights#185]
首先是意外这关常出意外，但有的时候又没事。
盯着看的时候发现mma在尝试部署，但多次拖到一半就松开了，接着几次尝试就会出现各种奇怪的部署位置，之后其他关卡也出现了这种问题尤其是带着多个地面单位/召唤系的时候
正常通过
![意外没有意外](https://user-images.githubusercontent.com/98801829/151934649-b7d8cf70-49b7-4751-b4bb-09e3c29203e9.png)
一些意外
![image](https://user-images.githubusercontent.com/98801829/151936245-52133530-e2e3-479c-82dd-0eacba2f5212.png)
![意外出了意外](https://user-images.githubusercontent.com/98801829/151934694-b8d99861-de64-453d-9c31-d749b2493ed5.png)
其他关卡
![image](https://user-images.githubusercontent.com/98801829/151936791-6846c06b-4510-42a8-907c-ab119c4fc853.png)
![image](https://user-images.githubusercontent.com/98801829/151937578-0ac28d62-c5f6-4f01-8724-53d7037d3edf.png)
其次是一个微不足道的的问题：mma不会招募安赛尔，于是我翻了一下，发现一个错别字
![安赛尔：安塞尔？](https://user-images.githubusercontent.com/98801829/151935531-f2e927bd-5c75-4d15-9c5d-af52edca819d.png)
*这还是我第一次发issue来着，希望这么多图片不会过于影响观感QwQ

**Comment by MistEO** [comment]
- 经常拖动到一半就松开：这种很可能是游戏帧数过低，我这里之前试过把游戏帧数设到 30（包括游戏内设置和模拟器设置），是高概率出现拖到到一半就放手的。问题原因暂时未知，可以先把帧数设到60或更高试试

**Comment by ShiuAsa** [comment]
夜神模拟器60帧，同样是这张图，在部署稀音的小车时也会拖到一半松开

**Comment by MistEO** [comment]
> 夜神模拟器60帧，同样是这张图，在部署稀音的小车时也会拖到一半松开

召唤物是已知问题（或者说是设计如此），干员正常即可~

**Comment by MeadalFlute** [comment]
> 

已解决，谢谢（｡ò ∀ ó｡）

**Comment by MistEO** [comment]
没别的问题的话 issue 我就关掉咯 (*´▽｀)ノノ
