### ISSUE TITLE
rougelike模式下投资到达上限后无限尝试投资

### ISSUE THREAD

**Issue by AsterNighT** [MistEO/MeoAssistantArknights#186]
模拟器：bluestack5 hyper-v
投资到达上限后卡在投资界面了，无限尝试投资
![image](https://user-images.githubusercontent.com/22937027/151938150-79e8444f-c6a4-48b6-be79-9d669480e24f.png)
![image](https://user-images.githubusercontent.com/22937027/151938068-bfa68962-99d0-4634-a27f-af08cb34c048.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7977023/asst.log)

**Comment by MistEO** [comment]
[v3.0.1](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v3.0.1) 版本已修复，请体验~
