### ISSUE TITLE
无限肉鸽 商店不自动投资

### ISSUE THREAD

**Issue by nvtijuewang** [MistEO/MeoAssistantArknights#187]
肉鸽后2种投资模式 进入1层商店会选择离开 不进投资功能
蓝mumu模拟器

![}D }W2L{@FLZ83$3IDR}%27](https://user-images.githubusercontent.com/98808955/151943865-7923c880-ba3f-4382-afb4-4505440723a7.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7977426/asst.log)

**Comment by MistEO** [comment]
确定当时商店是有投资系统的吗？麻烦附下日志吧

**Comment by nvtijuewang** [comment]
> 确定当时商店是有投资系统的吗？麻烦附下日志吧

我有开了一次  日志附上了 帮我看看什么问题

**Comment by MistEO** [comment]
> > 确定当时商店是有投资系统的吗？麻烦附下日志吧
> 
> 我又开了一次 日志附上了 帮我看看什么问题

你的分辨率有点奇怪，是 `1720x968`, 换个常见的 16:9 试试吧，比如 `1920x1080` 等的

**Comment by nvtijuewang** [comment]
> > > 确定当时商店是有投资系统的吗？麻烦附下日志吧
> > 
> > 
> > 我又开了一次 日志附上了 帮我看看什么问题
> 
> 你的分辨率有点奇怪，是 `1720x968`, 换个常见的 16:9 试试吧，比如 `1920x1080` 等的

谢谢 设置成1080p后功能正常

**Comment by MistEO** [comment]
没问题的话 issue 我就关掉咯 (*´▽｀)ノノ
