### ISSUE TITLE
夜神模拟器链接不上

### ISSUE THREAD

**Issue by a2251006690** [MistEO/MeoAssistantArknights#191]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7984089/asst.log)
![M$62UZOHJLMALAF$%9X}W87](https://user-images.githubusercontent.com/31102671/152105209-768e87b9-f321-4608-9d84-2d0acf8b0552.png)
![T`}I%AR8N_)8{X}DV U9QAR](https://user-images.githubusercontent.com/31102671/152105216-210d6b09-0462-4677-9250-875bfac086f1.png)
![VB3JFPT@MS3)}H4}MLLEE$G](https://user-images.githubusercontent.com/31102671/152105225-8fd1ea05-d859-4770-9f80-8d6d4ac959b7.png)
麻烦作者了

**Comment by a2251006690** [comment]
更换了蓝叠国际版正常了，麻烦作者了

**Comment by MistEO** [comment]
没别的问题的话 issue 我就关掉咯 (*´▽｀)ノノ
