### ISSUE TITLE
肉鸽此界面卡住，然后尝试取消探索

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#197]
![BS_PIC_2022-02-03-11-19-12](https://user-images.githubusercontent.com/76220347/152314879-60be1b12-38b4-465e-8f19-881a73bb5460.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7993237/asst.log)

新年快乐！

**Comment by MistEO** [comment]
[v3.0.1](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v3.0.1) 版本已修复，请体验~
