### ISSUE TITLE
凌晨四点刷新后肉鸽卡死

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#198]
![BS_PIC_2022-02-04-06-46-22](https://user-images.githubusercontent.com/76220347/152442811-f4bebef2-ed56-4b00-a091-14a55972971a.png)
![QQ截图20220204065124](https://user-images.githubusercontent.com/76220347/152442822-fd71e23e-b307-4848-8257-180d14e166eb.png)

Thanks♪(･ω･)ﾉ

**Comment by guojunyu196** [comment]
[asst.zip](https://github.com/MistEO/MeoAssistantArknights/files/7998831/asst.zip)
奇怪，直接上传asst.log怎么传不了

**Comment by MistEO** [comment]
[v3.0.1](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v3.0.1) 版本已修复，请体验~
