### ISSUE TITLE
挂机剿灭后结算不能正确识别

### ISSUE THREAD

**Issue by Ukua** [MistEO/MeoAssistantArknights#203]
剿灭打完后会有一个战斗简报，MAA会在此时停止思考然后尝试识别掉落
没看过源码，推测是没写相关逻辑点掉这个简报
(这个bug似乎不会影响挂机的正常进行)

模拟器截图:
![L2H1B@MI(T@HYYQ_(6R4PK9](https://user-images.githubusercontent.com/69282401/152674744-a1b61cd2-5798-4ca9-96ae-35e522d12f37.png)
MAA截图:
![image](https://user-images.githubusercontent.com/69282401/152674758-3e141f66-a03e-4220-a9be-3439feeb0663.png)

asst.log:
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8009851/asst.log)

**Comment by ABA2396** [comment]
剿灭的图企鹅物流没有，所以上报会出错

**Comment by MistEO** [comment]
这个问题是因为，你截图的这个界面，也能隐约看到“行动结束”，被识别到了 orz, 好像只有剿灭有这种情况，应该不也太影响。暂时不管了_(:з」∠)_

上传失败是因为企鹅物流不接剿灭的数据
