### ISSUE TITLE
解压到桌面后 每次打开MeoAsstGui.exe 软件都会白屏 然后闪退 

### ISSUE THREAD

**Issue by gguardians2** [MistEO/MeoAssistantArknights#205]
没找到asst.log文件    WIN10 mumu模拟器 原版
![L(~SPJMMVQ7B7C)NI8K({{Q](https://user-images.githubusercontent.com/99218375/152872420-fcae5542-6c6e-4db0-ac99-4cb11b4065b8.png)

**Comment by gguardians2** [comment]
开和不开模拟器的时候都白屏打不开

**Comment by MistEO** [comment]
请参考 `常见问题` - `软件闪退` 部分内容

**Comment by LuvEven** [comment]
> 开和不开模拟器的时候都白屏打不开

参考 `常见问题`  - `软件闪退` 中CPU的`AVX` 指令集问题，下载[NOAVX](https://github.com/MistEO/MeoAssistantArknights/blob/master/3rdparty/ppocr_noavx.zip)版本程序中的`PaddleOCR` 替换对应文件
