### ISSUE TITLE
肉鸽永远在第一层第一关打完后放弃

### ISSUE THREAD

**Issue by batjoker** [MistEO/MeoAssistantArknights#207]
issue：会在第一关打完以后选人的时候卡一会，然后整局放弃掉

请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8023191/asst.log)

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_
雷神64位（应该和雷电是一个东西） ，分辨率确实是16:9，
倒也不算出错，会一直不报错循环下去但是只会打一关，这样既不能刷钱也不能刷进度了……
![image](https://user-images.githubusercontent.com/12227240/152974660-a6b84a74-bca7-4486-b3b9-c4ef30f5ca4a.png)

Thanks♪(･ω･)ﾉ

**Comment by MistEO** [comment]
分辨率太低了，是 540p 的，换到 720p 或更高的试一下
