### ISSUE TITLE
3.0.1版本打开后，10秒不到自动关闭

### ISSUE THREAD

**Issue by deYangar** [MistEO/MeoAssistantArknights#208]
CPU：6700hq，支持AVX
系统：Win10专业版 21H1
模拟器：mumu

描述：3.0版本能正常使用，3.0.1版本下载下来后，第一次打开能正常使用，之后关掉再打开，就会在10秒内自动关闭。无论模拟器是否开启着。

以下是asst.log文件
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8026847/asst.log)

**Comment by MistEO** [comment]
看起来像是界面崩了，界面那边现在没有日志，看不出来啥问题。_(:з」∠)_ 把 gui.json 删了重新试试

**Comment by deYangar** [comment]
> 好像界面崩了，界面现在没有出现什么问题，看不出来啥问题_。_

按照你说的删除gui.json之后确实可以，重置了设置
但是如果设置里面设置了代理，就会闪退。而且就算下次手动在gui.json里面把代理那行全删了也会闪退。

如果 设置了代理，就会闪退，但是不修改gui.json，直接删掉的话，下次还能打开，只要不设置代理就能一直开
如果 设置了代理，闪退后，手动修改gui.json，删掉最底下代理那行设置，之后就一直闪退。就算删除了gui.json文件，也不行

**Comment by deYangar** [comment]
好像是因为，我这里的gui.json里面没有
"resource/penguin-stats-recognize/json/stages.json": "341529b3b349ebd71c6a7964562dd5f424ca3f2c",
  "resource/recruit.json": "341529b3b349ebd71c6a7964562dd5f424ca3f2c",
这两行
现在重下，覆盖，就算加了代理也能用。也能自动生成这两行

**Comment by MistEO** [comment]
搞定了的话，issue 我就关咯(*´▽｀)ノノ
