### ISSUE TITLE
重复执行基建换班

### ISSUE THREAD

**Issue by HaneRo** [MistEO/MeoAssistantArknights#209]
已经领取完任务奖励了还重复换班
![无标题](https://user-images.githubusercontent.com/26104114/153108138-0cef6f6e-7372-45be-9091-f8a9e8181b63.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8028823/asst.log)

**Comment by MistEO** [comment]
任务开始之前是不是 `LikeStart` 和 `停止` 来回点了几次。这块现在有点问题，连接模拟器成功之前再点停止就会出问题。没有修复计划，打算等新 UI 了
