### ISSUE TITLE
编译 bug 求助 `libdnnl.so.2` needed

### ISSUE THREAD

**Issue by KokeCacao** [MistEO/MeoAssistantArknights#216]
```
[ 96%] Linking CXX shared library libMeoAssistant.so
[ 96%] Built target MeoAssistant
Scanning dependencies of target test
[ 98%] Building CXX object CMakeFiles/test.dir/tools/TestCaller/main.cpp.o
[100%] Linking CXX executable test
/usr/bin/ld: warning: libdnnl.so.2, needed by //home/koke_cacao/Documents/Koke_Cacao/CPP/WorkSpace/paddle_inference/paddle/lib/libpaddle_inference.so, not found (try using -rpath or -rpath-link)
//home/koke_cacao/Documents/Koke_Cacao/CPP/WorkSpace/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `dnnl_primitive_attr_set_scales'
libMeoAssistant.so: undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Rect_<int> const&)'
//home/koke_cacao/Documents/Koke_Cacao/CPP/WorkSpace/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `dnnl_primitive_destroy'
//home/koke_cacao/Documents/Koke_Cacao/CPP/WorkSpace/paddle_inference/paddle/lib/libpaddle_inference.so: undefined reference to `dnnl_primitive_desc_query'
libMeoAssistant.so: undefined reference to `cv::boundingRect(cv::_InputArray const&)'
```

我的尝试:
1. 因为 `PaddleORC` depends on `paddle_inference`, 我看 `PaddleORC` 里 `CMakeLists.txt` 没有提到 `libdnnl.so.2`, 于是我加了上去. 没效果.
2. 编译 MeoAssistant 时加了一行 `find_library(DNNL_LIB NAMES dnnl PATHS /home/koke_cacao/Documents/Koke_Cacao/CPP/WorkSpace/paddle_inference/third_party/install/mkldnn/lib)` 后说找不到文件
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
DNNL_LIB
    linked by target "MeoAssistant" in directory /home/koke_cacao/Documents/Koke_Cacao/CPP/WorkSpace/MeoAssistantArknights
```
3. 把整个 `paddle_inference` 文件夹考入 `/usr/lib` 然后 `dlconfig`. 没效果
4. 直接 `make` 行不通

求正确装 `paddle_inference` 的方式

**Comment by MistEO** [comment]
paddleocr 的 cmake 里，有拷贝 paddle_inference 依赖的第三方库的操作，[在这里](https://github.com/MistEO/PaddleOCR/blob/release/2.3/deploy/cpp_infer/CMakeLists.txt#L126)，尝试用 sudo 执行 cmake 看看

**Comment by bakashigure** [comment]
试试复制``paddle_inference/third_party/install/mkldnn/lib/libdnnl.so.2``到``/usr/lib``

**Comment by KokeCacao** [comment]
> 试试复制`paddle_inference/third_party/install/mkldnn/lib/libdnnl.so.2`到`/usr/lib`

试了, 不行呢. (有重启shell)

**Comment by KokeCacao** [comment]
> paddleocr 的 cmake 里，有拷贝 paddle_inference 依赖的第三方库的操作，[在这里](https://github.com/MistEO/PaddleOCR/blob/release/2.3/deploy/cpp_infer/CMakeLists.txt#L126)，尝试用 sudo 执行 cmake 看看

```
(base) ➜  mkldnn tree
.
├── include
│   ├── dnnl_config.h
│   ├── dnnl_debug.h
│   ├── dnnl.h
│   ├── dnnl.hpp
│   ├── dnnl_ocl.h
│   ├── dnnl_ocl.hpp
│   ├── dnnl_sycl.h
│   ├── dnnl_sycl.hpp
│   ├── dnnl_sycl_types.h
│   ├── dnnl_threadpool.h
│   ├── dnnl_threadpool.hpp
│   ├── dnnl_threadpool_iface.hpp
│   ├── dnnl_types.h
│   ├── dnnl_version.h
│   ├── mkldnn_config.h
│   ├── mkldnn_debug.h
│   ├── mkldnn_dnnl_mangling.h
│   ├── mkldnn.h
│   ├── mkldnn.hpp
│   ├── mkldnn_types.h
│   ├── mkldnn_version.h
│   └── oneapi
│       └── dnnl
│           ├── dnnl_config.h
│           ├── dnnl_debug.h
│           ├── dnnl.h
│           ├── dnnl.hpp
│           ├── dnnl_ocl.h
│           ├── dnnl_ocl.hpp
│           ├── dnnl_sycl.h
│           ├── dnnl_sycl.hpp
│           ├── dnnl_sycl_types.h
│           ├── dnnl_threadpool.h
│           ├── dnnl_threadpool.hpp
│           ├── dnnl_threadpool_iface.hpp
│           ├── dnnl_types.h
│           └── dnnl_version.h
└── lib
    ├── libdnnl.so.1 -> libmkldnn.so.0
    ├── libdnnl.so.2 -> libmkldnn.so.0
    └── libmkldnn.so.0
```

`cp -r ${PADDLE_LIB}/third_party/install/mklml/lib/libmklml_intel${CMAKE_SHARED_LIBRARY_SUFFIX} /usr/lib` 执行应该会出错. 我没有见到 `libmklml_intel` 这个问题

**Comment by MistEO** [comment]
>> 
> sudo 的话是这样的
> 
> ```
> (base) ➜  cpp_infer git:(release/2.3) ✗ sudo su         
> [sudo] password for koke_cacao: 
> KokeCacao-Ubuntu# ./tools/build.sh 
> ./tools/build.sh: 10: ./tools/build.sh: cmake: not found
> make: *** 没有指明目标并且找不到 makefile。 停止。
> KokeCacao-Ubuntu# exit
> (base) ➜  cpp_infer git:(release/2.3) ✗ sudo ./tools/build.sh
> ./tools/build.sh: 10: ./tools/build.sh: cmake: not found
> make: *** No targets specified and no makefile found.  Stop.
> 
> # 在build.sh文件里面添加sudo后...
> (base) ➜  cpp_infer git:(release/2.3) ✗ ./tools/build.sh 
> sudo: cmake: command not found
> make: *** No targets specified and no makefile found.  Stop.
> ```


这个报错说 cmake 找不到呀，不是编译的问题

**Comment by KokeCacao** [comment]
> > > 
> > 
> > 
> > sudo 的话是这样的
> > ```
> > (base) ➜  cpp_infer git:(release/2.3) ✗ sudo su         
> > [sudo] password for koke_cacao: 
> > KokeCacao-Ubuntu# ./tools/build.sh 
> > ./tools/build.sh: 10: ./tools/build.sh: cmake: not found
> > make: *** 没有指明目标并且找不到 makefile。 停止。
> > KokeCacao-Ubuntu# exit
> > (base) ➜  cpp_infer git:(release/2.3) ✗ sudo ./tools/build.sh
> > ./tools/build.sh: 10: ./tools/build.sh: cmake: not found
> > make: *** No targets specified and no makefile found.  Stop.
> > 
> > # 在build.sh文件里面添加sudo后...
> > (base) ➜  cpp_infer git:(release/2.3) ✗ ./tools/build.sh 
> > sudo: cmake: command not found
> > make: *** No targets specified and no makefile found.  Stop.
> > ```
> 
> 这个报错说 cmake 找不到呀，不是编译的问题

Okay. 我没解释清楚. 我的意思是就算 sudo cmake 成功运行, 也不会自动拷贝 `libdnnl.so.2` 这个文件. 你标亮的那一行是拷贝 `libmklml_intel`.

我现在已经把所有 paddleORC 的错误修好了, 一样不行呢. 还是说找不到 `libdnnl.so.2`

**Comment by KokeCacao** [comment]
最后 `link_directories(/path/to/paddle_inference/third_party/install/mkldnn/lib)` 解决的. 

另外, 似乎 `target_link_libraries(MeoAssistant ${OpenCV} ${PaddleOCR_LIB} ${Penguin_LIB} ${ZLIB})` 要改成 `target_link_libraries(MeoAssistant ${OpenCV_LIBS} ${PaddleOCR_LIB} ${Penguin_LIB} ${ZLIB})`. 还要加一句 `include_directories(${OpenCV_INCLUDE_DIRS})`

`.zshrc` 里找不到 `libdnnl.so.2` 还需要添加以下系统才找得到
```
# Normally you will add the path to /etc/ld.so.conf.d in Ubuntu, but since this is a hack, I will add it as environment variable
LD_LIBRARY_PATH=/path/to/paddle_inference/third_party/install/mkldnn/lib/$
export LD_LIBRARY_PATH
```
