### ISSUE TITLE
任务出错

### ISSUE THREAD

**Issue by MXTRichard** [MistEO/MeoAssistantArknights#218]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8053660/asst.log)
蓝叠模拟器
一开始连接失败，按着说明设置了连接设置，没怎么看懂，感觉输入的不对
![QQ截图20220212224710](https://user-images.githubusercontent.com/51512279/153715955-3a9c9976-a152-4651-b452-209daf3e9cce.jpg)
然后运行时任务出错
![QQ截图20220212224742](https://user-images.githubusercontent.com/51512279/153715985-8854b590-8fc3-4b6a-a89f-48e36f7350b0.jpg)
![QQ截图20220212224847](https://user-images.githubusercontent.com/51512279/153716015-9c2fb5fa-9248-4422-bd2f-c354fab5ae6e.jpg)

**Comment by MistEO** [comment]
连接设置里的选项，不知道是啥意思就不需要填的

**Comment by MXTRichard** [comment]
填的内容都删了还是会任务出错
![QQ截图20220213022947](https://user-images.githubusercontent.com/51512279/153723759-12d937c6-9462-4ec9-a406-ffb9afe2adcf.jpg)

**Comment by MistEO** [comment]
> 蓝叠模拟器国际版（推荐使用）
> 完美支持。需要在模拟器 设定 - 进阶 中打开 Android调试桥

是不是这个没开

**Comment by MXTRichard** [comment]
我憨了，原来用mumu链接错误，换了蓝叠忘记看说明了就没打开

**Comment by MXTRichard** [comment]
谢谢
