### ISSUE TITLE
关卡选择的建议

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#219]
[资源关卡时间排表.docx](https://github.com/MistEO/MeoAssistantArknights/files/8053911/default.docx)
![OF9MNB5 T$2P@%J M@E4{A](https://user-images.githubusercontent.com/76220347/153718034-bc4250dc-bc13-4429-b2ac-26f66d9308c1.png)
将时间表加到红框空出来的地方，这样就可以不用算今天开哪关了（

**Comment by MistEO** [comment]
好主意，之后版本加上！

**Comment by MistEO** [comment]
v3.0.3 版本已经加啦（虽然现在很丑_(:з」∠)_
