### ISSUE TITLE
自动更新错误

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#223]
手动重新下载3.03后，（更新后）打开软件，出现更新提示
![屏幕截图 2022-02-15 080152](https://user-images.githubusercontent.com/76220347/153969450-ca437e95-db6b-4f33-98ae-faa96fbb24ca.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8064809/asst.log)

**Comment by hjhjfhjhujhh** [comment]
你进到设置，可以看到真实的版本号是3.0.2，大概是作者releases页面上传成3.0.3了，于是就出现了这种bug...

**Comment by MistEO** [comment]
fixed~
