### ISSUE TITLE
公开招募一次只使用三个槽

### ISSUE THREAD

**Issue by hjhjfhjhujhh** [MistEO/MeoAssistantArknights#227]
如题...我观察到这个BUG已经有一段时间了，但是经过数个版本更迭后依然存在...只有我有这个问题吗？
再次使用招募功能可以正常使用剩下的槽。
log文件已清空。使用模拟器：蓝叠国际版（hyperV）
![LW{VC_72D(7N%`3S7A FV`B](https://user-images.githubusercontent.com/89215821/154001102-b7098bd7-0cea-4d29-a446-5ebbdcd10eba.png)
LOG：[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8066198/asst.log)

**Comment by hjhjfhjhujhh** [comment]
还是说这是某种特性？

**Comment by MistEO** [comment]
设置里可以设的，最大招募次数那个选项 2333

**Comment by tangtang233** [comment]
<img width="590" alt="Snipaste_2022-02-15_21-47-39" src="https://user-images.githubusercontent.com/24298787/154075242-adc43941-9136-426f-b440-5683a71b2a65.png">
这里默认是3，你改成4应该就可以了。

**Comment by hjhjfhjhujhh** [comment]
草，怎么这个问题没close
