### ISSUE TITLE
夜神国际版适配

### ISSUE THREAD

**Issue by Etherrrr** [MistEO/MeoAssistantArknights#228]
"Nox": {
            "handle": {
                "class": "Qt5QWindowIcon",
                "window": "夜神模拟器"
            },
            "adb": {
                "path": "[EmulatorPath]nox_adb.exe",
                "addresses": [
                    "127.0.0.1:62001",
                    "127.0.0.1:59865"
                ],
                "devices": "[Adb] devices",
                "addressRegex": "(.+)\tdevice",
                "connect": "[Adb] connect [Address]",
                "click": "[Adb] -s [Address] shell input tap [x] [y]",
                "swipe": "[Adb] -s [Address] shell input swipe [x1] [y1] [x2] [y2] [duration]",
                "display": "[Adb] -s [Address] shell dumpsys window displays | grep init= | awk ' { print $3 } '",
                "displayFormat": "cur=%dx%d",
                "screencapRawWithGzip": "[Adb] -s [Address] exec-out \"screencap | gzip -1\"",
                "screencapEncode": "[Adb] -s [Address] exec-out screencap -p",
                "release": "[Adb] kill-server"
            }
        },
中`"window": "夜神模拟器"`处修改为`"window": "NoxPlayer"`即可

不过每次升级就会自动覆盖掉修改后的设置……希望作者直接把国际版的整合进去😓

**Comment by MistEO** [comment]
ok, 感谢反馈，下版本加上~
