### ISSUE TITLE
似乎是版本号的问题？每次启动都要提醒一次3.03版本更新

### ISSUE THREAD

**Issue by OrangeCh** [MistEO/MeoAssistantArknights#230]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

Thanks♪(･ω･)ﾉ
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8068502/asst.log)
![image](https://user-images.githubusercontent.com/9038816/154049808-6a7d3288-53d3-4617-abb1-11d55f8204e3.png)
![image](https://user-images.githubusercontent.com/9038816/154049927-ce9fd438-48aa-48ff-9c89-7135feb91ba9.png)

**Comment by MistEO** [comment]
v3.0.4 fixed~

**Comment by OrangeCh** [comment]
刚刚发现已经修复了，感谢！
