### ISSUE TITLE
活动期间选择战斗关卡时发生错误

### ISSUE THREAD

**Issue by ABA2396** [MistEO/MeoAssistantArknights#231]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8068675/asst.log)
![QWDT1$AO36`87JTX@P8R9$I](https://user-images.githubusercontent.com/99072975/154054441-218beaf8-d63c-40cb-9c80-5d529af21ab5.png)
![K 8B ~IY33 {_74O%10N9`6](https://user-images.githubusercontent.com/99072975/154054447-3eaa8eb1-c03c-4229-863e-60d4e97cc6aa.png)

**Comment by ABA2396** [comment]
![QWDT1$AO36`87JTX@P8R9$I](https://user-images.githubusercontent.com/99072975/154054522-2d3b9b3c-71fe-44a2-b48d-2d871c2cd662.png)

**Comment by MistEO** [comment]
~~等活动过完这个 bug 就自动修复了~~

**Comment by MistEO** [comment]
活动结束，我关！
