### ISSUE TITLE
刷图时任务异常中止

### ISSUE THREAD

**Issue by ABA2396** [MistEO/MeoAssistantArknights#233]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8081063/asst.log)
![AXGZWMUDO21T8LR(%F WO2T](https://user-images.githubusercontent.com/99072975/154296927-31fcf717-6baf-4317-af2b-c6330b0b2309.png)

**Comment by MistEO** [comment]
v3.0.5 fixed
