### ISSUE TITLE
MAA在刷完两把作战之后异常关闭

### ISSUE THREAD

**Issue by ErioRUA** [MistEO/MeoAssistantArknights#236]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8088363/asst.log)
模拟器是蓝叠国际版

**Comment by MistEO** [comment]
3.0.4 版本修了这个问题，试试看有没有效果

**Comment by MistEO** [comment]
v3.0.5 再试着修复了一下，再试试 QAQ
