### ISSUE TITLE
未勾选更新测试版功能仍旧会下载新的测试版本

### ISSUE THREAD

**Issue by LuvEven** [MistEO/MeoAssistantArknights#238]
一点小问题，之前好像也有人提过
![image](https://user-images.githubusercontent.com/56387141/154603058-119a0e84-e4c1-4253-950f-2a4ebc81f00d.png)
![image](https://user-images.githubusercontent.com/56387141/154603245-48a02b39-85c2-42fd-9317-aa43294fbe88.png)

**Comment by MistEO** [comment]
不是测试版本了，这俩都是正式版本
