### ISSUE TITLE
在刷取近卫特种芯片时固定两把闪退

### ISSUE THREAD

**Issue by one-pyy** [MistEO/MeoAssistantArknights#240]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8102087/asst.log)
好像和掉落的芯片种类没有关系(相同芯片、不同芯片都闪退), 但企鹅物流好像都上传错误了

**Comment by MistEO** [comment]
新版本修复了几个关卡掉落识别导致的崩溃问题，试试看有没有用，v3.0.4 的

**Comment by MistEO** [comment]
v3.0.5 再试着修复了一下，再试试 QAQ

**Comment by one-pyy** [comment]
![image](https://user-images.githubusercontent.com/72590023/154822348-c2b5555e-9b02-4255-83af-a6bedaf2a657.png)
不闪退了\(^_^)/

**Comment by MistEO** [comment]
不闪退了但是没有识别结果了 orz 我继续修

**Comment by MistEO** [comment]
v3.0.6 fixed

**Comment by one-pyy** [comment]
好耶ヾ(✿ﾟ▽ﾟ)ノ
