### ISSUE TITLE
3.05作战识别失败

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#242]
![7NN73J_RY(~DQF4C5FVPOIS](https://user-images.githubusercontent.com/76220347/154828217-8842204b-fa42-4a09-b96f-56142cb5c62e.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8103422/asst.log)

Thanks♪(･ω･)ﾉ

**Comment by MistEO** [comment]
v3.0.6 fixed
