### ISSUE TITLE
周回体力时多次提示任务出错并中断

### ISSUE THREAD

**Issue by Mashiro173** [MistEO/MeoAssistantArknights#243]
蓝叠国际版
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8103730/asst.log)

**Comment by MistEO** [comment]
麻烦问题描述清楚一些吧

**Comment by Mashiro173** [comment]
![image](https://user-images.githubusercontent.com/98558933/154837646-1991bd72-0142-4733-814c-55435774b35e.png)
就是周回任务进行到一半 模拟器在打1-7 右下角弹窗提示任务已经全部完成 助手的界面上提示任务出错

**Comment by MistEO** [comment]
游戏停在哪个界面了？

**Comment by Mashiro173** [comment]
> 

还在刷1-7 大概第10个怪左右

**Comment by Mashiro173** [comment]
![image](https://user-images.githubusercontent.com/98558933/154838745-e0f6ad8e-ad88-4aeb-af0b-485004aaea20.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8103786/asst.log)

又碰到一次 这是日志

**Comment by MistEO** [comment]
v3.0.6 fixed
