### ISSUE TITLE
无法刷理智

### ISSUE THREAD

**Issue by bubububaoshe** [MistEO/MeoAssistantArknights#251]
我这里OS是win11中文版，meo版本号3.0.6，游戏客户端夜神模拟器7.0.2，
刷理智时没有任何反应，但是其他功能都可以运行
我在3.0.4时也碰到过同样问题，都是一开始刷理智没问题，但meo和客户端都没动的情况下，某一天突然不能刷了，重启无效
log如附件，请问这是什么问题呢？谢谢
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8126425/asst.log)

**Comment by bubububaoshe** [comment]
Sorry，是我关卡选择成了“当前关卡”导致的（话说这个选项有什么用啊XD)

**Comment by qianxu2001** [comment]
> Sorry，是我关卡选择成了“当前关卡”导致的（话说这个选项有什么用啊XD)

你手动进到关卡选择界面，点击关卡，但是不点开始战斗，这个当前关卡就会一直帮你刷这关

**Comment by bubububaoshe** [comment]
> 

嗯嗯，但是如果你点击开始战斗，然后选择“上次作战”，感觉效果是完全一样的

**Comment by bubububaoshe** [comment]
> > Sorry，是我关卡选择成了“当前关卡”导致的（话说这个选项有什么用啊XD)
> 
> 你手动进到关卡选择界面，点击关卡，但是不点开始战斗，这个当前关卡就会一直帮你刷这关

嗯嗯，但是如果你点击开始战斗，然后选择“上次作战”，感觉效果是完全一样的
所以我就有点质疑这个选项存在的必要:)
