### ISSUE TITLE
关于连接手机的问题

### ISSUE THREAD

**Issue by hjhjfhjhujhh** [MistEO/MeoAssistantArknights#257]
windows平台，这软件究竟怎么连接手机？控制台adb devices能连接上，但是使用软件连接就会提示失败
软件设置里的自定义地址填什么？adb devices显示的没有IP地址而是设备名，输入手机的wifi ip也不行
（已经把platform-tools放到该放的地方了）

**Comment by MistEO** [comment]
USB 就输入设备名。WIFI 为啥不行，来个日志康康

**Comment by hjhjfhjhujhh** [comment]
> USB就输入设备名。WIFI为啥不行，来个日志康康
直接输入设备名就行了吗？
wifi好像是我设备的问题，控制台adb也连不了

**Comment by hjhjfhjhujhh** [comment]
> USB就输入设备名。WIFI为啥不行，来个日志康康

啊啊，在数次重启软件之后就莫名其妙地成功连接了，抱歉打扰了
在使用说明里加上连接手机的方法吧，软件里面写的是“自定义地址”，没想到要输入设备名，还以为必须是ip地址呢
而且，貌似地址栏无论输入什么，启动软件都不会报错的样子（直接开始任务），是bug吗

**Comment by MistEO** [comment]
> > USB就输入设备名。WIFI为啥不行，来个日志康康
> 
> 啊啊，在数次重启软件之后就莫名其妙地成功连接了，抱歉打扰了 在使用说明里加上连接手机的方法吧，软件里面写的是“自定义地址”，没想到要输入设备名，还以为必须是ip地址呢 而且，貌似地址栏无论输入什么，启动软件都不会报错的样子（直接开始任务），是bug吗

连接失败的时候会调用 `adb devices` 自动查找可用设备的 (*´▽｀)ノノ

USB 连接的设备是可以直接被查找到的，所以你随便乱填一个都行；局域网设备查不到，所以必须得手动填。

**Comment by hjhjfhjhujhh** [comment]
> > > USB就输入设备名。WIFI为啥不行，来个日志康康
> > 
> > 
> > 啊啊，在数次重启软件之后就莫名其妙地成功连接了，抱歉打扰了 在使用说明里加上连接手机的方法吧，软件里面写的是“自定义地址”，没想到要输入设备名，还以为必须是ip地址呢 而且，貌似地址栏无论输入什么，启动软件都不会报错的样子（直接开始任务），是bug吗
> 
> 连接失败的时候会调用 `adb devices` 自动查找可用设备的 (*´▽｀)ノノ
> 
> USB 连接的设备是可以直接被查找到的，所以你随便乱填一个都行；局域网设备查不到，所以必须得手动填。

啊这，我不填设备名的话好像会报错耶
嗯......既然现在能用了就还是把串关了吧
