### ISSUE TITLE
公招不会使用最后一个槽位

### ISSUE THREAD

**Issue by breathiness** [MistEO/MeoAssistantArknights#268]
![Clip_20220306_144520](https://user-images.githubusercontent.com/11361630/156913721-6d13cc04-162c-41b1-873f-05fd30b7dcfc.png)
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8192139/asst.log)

**Comment by MistEO** [comment]
设置里可以改的，`最大公招次数`，默认是 3
