### ISSUE TITLE
刷理智任务出错

### ISSUE THREAD

**Issue by ABA2396** [MistEO/MeoAssistantArknights#279]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8222243/asst.log)

https://user-images.githubusercontent.com/99072975/157637649-ceed9e73-c86b-4a15-9ff3-5450c33df298.mp4

**Comment by MistEO** [comment]
初步猜是缓存影响的，但是日志不完整，看不到前面有没有缓存的记录_(:з」∠)_下次最好把整个日志拖上来

**Comment by PlayerMo** [comment]
我今天刷芯片也是这样

**Comment by MistEO** [comment]
v3.0.7 fixed
