### ISSUE TITLE
“刷理智”功能只统计第一次的掉落物

### ISSUE THREAD

**Issue by YOUQY979** [MistEO/MeoAssistantArknights#285]
刷理智功能只会统计第一次的掉落物，从第2次开始都不显示，也不显示总的统计。
之前用MUMU，现在用蓝叠国际版，都有这个问题。
好像从上上个版本开始就有这问题了，不知道是什么原因

![无标题](https://user-images.githubusercontent.com/25796318/158101546-8bfbd63a-799f-4a19-aa87-290e915047b3.png)
日志：
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8241573/asst.log)

**Comment by MistEO** [comment]
v3.0.6 已经修复了，更新一下吧~
