### ISSUE TITLE
助手更新后无法连接mumu模拟器

### ISSUE THREAD

**Issue by misakiycy** [MistEO/MeoAssistantArknights#289]
请附上助手软件目录下的`asst.log`日志文件，是可以直接拖拽进来的。
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8255528/asst.log)
最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_
使用的mumu模拟器，今天更新助手后显示无法连接模拟器，之后尝试过3.06与3.07版本均无法连接，安装adb后也不确定自定义地址，使用127.0.0.1:5555无效
Thanks♪(･ω･)ﾉ

**Comment by MistEO** [comment]
之前的版本可以连接？是哪个版本呀

mumu 的地址应该是 `127.0.0.1:7555`

**Comment by misakiycy** [comment]
之前用的3.0.6 也试过7555端口，也连接不了
不同之处在于今天更新了clash 0.19.12版本，但clash回退0.19.11版本还是无法连接

**Comment by MistEO** [comment]
> 之前用的3.0.6 也试过7555端口，也连接不了 不同之处在于今天更新了clash 0.19.12版本，但clash回退0.19.11版本还是无法连接

发个 7555 连接不上的日志康康_(:з」∠)_

不行就换个模拟器吧，mumu 就算连上了也可能有奇奇怪怪的问题 orz

**Comment by misakiycy** [comment]
> 
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/8255702/asst.log)
我也不知道和clash有什么关系，就当是控制变量法了（

**Comment by MistEO** [comment]
adb 的路径似乎不对，再确认下_(:з」∠)_

> 下载 [adb](https://dl.google.com/android/repository/platform-tools-latest-windows.zip) ，将 platform-tools 文件夹解压到 MeoAsstGui.exe 的同级目录

**Comment by MistEO** [comment]
adb 的路径似乎不对，再确认下_(:з」∠)_

> 下载 [adb](https://dl.google.com/android/repository/platform-tools-latest-windows.zip) ，将 platform-tools 文件夹解压到 MeoAsstGui.exe 的同级目录

**Comment by misakiycy** [comment]
我发现了，我直接把里面的文件解压出去了，少了外面的文件夹，我是弱智（
谢谢您的解答，不过为什么突然就连不上了呢（不是
