### ISSUE TITLE
希望增加一个理智药全磕完的功能吧

### ISSUE THREAD

**Issue by Mechant-Meets-The-Wise-Wolf** [MistEO/MeoAssistantArknights#296]
假如我全选
![image](https://user-images.githubusercontent.com/82165093/158749503-7c52d1de-7c30-4155-a0dd-0e3772827548.png)
，有时候不知道自己有多少理智药，想直接让它用完。

**Comment by MistEO** [comment]
所以默认的 999 不就可以了_(:з」∠)_

**Comment by Mechant-Meets-The-Wise-Wolf** [comment]
> 

我还以为选多了会出bug什么的……

**Comment by Mechant-Meets-The-Wise-Wolf** [comment]
> 所以默认的 999 不就可以了_(:з」∠)_

我还以为会出bug什么的……
