### ISSUE TITLE
wine-6.15无法启动MeoAsstGui.exe主程序

### ISSUE THREAD

**Issue by Team-Fortuna** [MistEO/MeoAssistantArknights#30]
OS: Pop!_OS 20.04 LTS x86_64 
Host: 82MS Yoga 14sACH 2021 
Kernel: 5.13.0-7614-generic 
Wine-version: wine-6.15

在terminal中执行 
```
cd ./MeoAssistance/
wine MeoAssistance.exe
```
[start.log](https://github.com/MistEO/MeoAssistance-Arknights/files/7447532/start.log)

附上启动日志

**Comment by MistEO** [comment]
初步完成了跨平台移植，简单整了个[文档](https://github.com/MistEO/MeoAssistantArknights/blob/cross_platform/src/MeoAssistant/Linux%E7%BC%96%E8%AF%91%E6%95%99%E7%A8%8B.md)，后面我再进一步完善下_(:з」∠)_
