### ISSUE TITLE
公招出错

### ISSUE THREAD

**Issue by popukar** [MistEO/MeoAssistantArknights#48]
识别此tag会显示识别错误，偶尔也会有这种情况
![Screenshot_2021-11-24-22-32-44-504_com hypergryph arknights](https://user-images.githubusercontent.com/54406127/143258971-af7ceb98-db6e-4150-85d8-e35bb41827bb.jpg)

**Comment by MistEO** [comment]
算是已知问题了，我自己也经常遇到orz
现在用的OCR库不太给力，经常识别错，准备找个时间换个别的_(:з」∠)_

~~在做了在做了（新建文件夹~~

**Comment by MistEO** [comment]
请体验 https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.4.1 版本
