### ISSUE TITLE
基建换班中异格干员判断有问题

### ISSUE THREAD

**Issue by manshisan** [MistEO/MeoAssistantArknights#56]
比如说炎熔，我发电站最高有异格炎熔，源石最高的有普通炎熔，换班的时候就会发生：在制造站把普通炎熔加进去后，在发电站又会把异格炎熔加进去，于是卡死在了确认界面的情况。

**Comment by MistEO** [comment]
居然还有这种问题_(:з」∠)_不知道怎么解决了orz

**Comment by manshisan** [comment]
😂

**Comment by zhang930427** [comment]
> 确实还有这种问题_(:з」∠)_不知道怎么解决了orz

直接手动设定组合，然后保存以后每个都按照组合添加 。

**Comment by litchiar** [comment]
也遇到了这个问题，一个简单的方法是判断换班是有没有弹出那个确认换班的框，就是右下角有没有确定按钮。至少能保证不被卡住循环

**Comment by MistEO** [comment]
临时解决了一下，目前只有 `炎狱炎熔` 有这个问题，我直接 ban 了她（

**Comment by MistEO** [comment]
[v2.7.8](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.7.8) 已修复卡住的问题，并添加对应的错误提示。请尝试~
