### ISSUE TITLE
反馈BUG请附上日志文件，谢谢~

### ISSUE THREAD

**Issue by MistEO** [MistEO/MeoAssistantArknights#62]
软件目录下的`asst.log`日志文件（是可以直接拖进来的）

最好再能说明下使用的模拟器、并附上出错时的游戏和软件的截图（要是没截到就算啦_(:з」∠)_

感谢！✿✿ヽ(°▽°)ノ✿

**Comment by MistEO** [comment]
置顶！

**Comment by miyouzi** [comment]
可以弄 issue 模板呀
