### ISSUE TITLE
基建控制中心出错，重复取消选择

### ISSUE THREAD

**Issue by feiqingbiss** [MistEO/MeoAssistantArknights#65]
![image](https://user-images.githubusercontent.com/36787768/145586308-9fbe0e5f-7976-47c2-9f76-106671c691e6.png)
[asst.log](https://github.com/MistEO/MeoAssistance-Arknights/files/7693248/asst.log)
新人玩家，只有五个控制中心干员，程序在跑到控制中心的时候一直重复取消选择，取消操作再重新进控制中心，无论干员是否疲劳。

**Comment by MistEO** [comment]
目前新版本应该不会死循环了。

但是如果可用干员不足，还是会选不满人，有几个选几个。现在的框架得改改，没考虑到这点。

**Comment by MistEO** [comment]
[测试版本](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.7.1) 已修复，请期待正式版本~
