### ISSUE TITLE
收取信用，无人机，宿舍换班相关问题

### ISSUE THREAD

**Issue by popukar** [MistEO/MeoAssistantArknights#72]
大佬你好，我在15号这天发现了如题所诉的相关问题：
- 收取信用是停顿在了好友列表页面，不进行好友访问
- 无人机的使用则是直接跳过了该环节
- 宿舍换班有时会遗漏心情低的干员，也会用满心情干员填满宿舍

附上文件
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7720572/asst.log)
使用的是夜神模拟器

感谢大佬的辛勤付出(/≧▽≦)/

**Comment by MistEO** [comment]
分辨率太低啦，换720p或以上试试，低分辨率识别效果不是很好

**Comment by popukar** [comment]
谢谢，提高到720后确实没问题了
