### ISSUE TITLE
更新OCR后，打开就闪退，无法使用

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#74]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7728286/asst.log)

**Comment by MistEO** [comment]
资源好像出错了，可能是没下载成功。手动重新下载下再看看？

**Comment by guojunyu196** [comment]
重新下载后，稳定版（2.3.6）运行正常，测试版（2.4.1）打开后依然闪退，甚至没有创建日志文件

**Comment by MistEO** [comment]
2.4及之后的版本，手动下载还是崩溃吗？

因为现在出现的比较少，我自己也没遇到，不知道是啥问题。

方便的话加下Q群吧，672372860，到时候我编几个版本出来，帮忙验证下有没有用。

**Comment by MistEO** [comment]
已提供兼容方案，请参考 [可能性 2: CPU 指令集不支持](https://github.com/MistEO/MeoAssistantArknights/tree/dev#%E8%BD%AF%E4%BB%B6%E4%B8%80%E6%89%93%E5%BC%80%E5%B0%B1%E9%97%AA%E9%80%80) 进行操作
