### ISSUE TITLE
刷理智和进程残留的问题及一些建议

### ISSUE THREAD

**Issue by usaginya** [MistEO/MeoAssistantArknights#75]
## 刷理智的建议

问题：看起来 当前刷理智会自动刷上一次作战的关卡、所以当上次把剿灭关卡刷完时、上次关卡会是剿灭、所以还是会开始刷剿灭关卡、造成不必要的理智浪费

建议：刷理智的时候检查一下是否是剿灭关卡、如果是剿灭关卡的话判断一下是不是已经刷完剿灭了、如果刷完了就提示换个关卡或者用其它方法改变刷理智方式、避免理智浪费在已刷好的剿灭关卡上

## 进程残留的问题

发现当关闭 `MeoAsstGui` 的时候虽然窗口已经消失、但在任务管理器进程中还是有 `MeoAsstGui.exe` 进程存在、即使已经离关闭经过了很长一段时间、进程仍然存在
不知道是不是特殊设计的、比如为了快速启动程序而做的缓存？不过感觉一般不会有这种设计吧 (^-^")

## 其他的建议

如果可以的话建议在一键长草任务结束后播放一段提示音、这样会更方便知道任务完成情况、当然也可以在设置中加个是否使用提示音的开关、避免一些场景下的打扰
我会在附件中提供一个完成提示音的 mp3 文件示例

### 其它信息
> 操作系统：Windows 7 旗舰版 sp1
> 模拟器：雷电4.0 x64 - 16:9 (1440x810) - DPI 210

---
忘记放附件了 (草ww
附件竟然支持 mp4 却不支持 mp3？
[clearComplete.zip](https://github.com/MistEO/MeoAssistantArknights/files/7740353/clearComplete.zip)
......压缩了一下

**Comment by MistEO** [comment]
- 刷理智的问题：目前从主界面进去的就是会刷上一次的关卡。如果是放在`蓝色开始按钮`的界面，就会刷当前关卡。选关功能正在做了
- 进程残留：是的，adb 子进程泄露了导致的，https://github.com/MistEO/MeoAssistantArknights/issues/53，暂时没啥排查方向_(:з」∠)_
- 播放提示音：好主意！直接用 Win10 的 Notify 就好了，之后版本加上！

**Comment by usaginya** [comment]
> * 刷理智的问题：目前从主界面进去的就是会刷上一次的关卡。如果是放在`蓝色开始按钮`的界面，就会刷当前关卡。选关功能正在做了
> * 进程残留：是的，adb 子进程泄露了导致的，[软件退出后，ADB子进程未释放 #53](https://github.com/MistEO/MeoAssistantArknights/issues/53) ，暂时没啥排查方向_(:з」∠)_
> * 播放提示音：好主意！直接用 Win10 的 Notify 就好了，之后版本加上！

- 但 `一键长草` 功能的目标是不需要有其他的操作介入、所以还是等大佬把选关功能做好吧_(:з」∠)_ 另外剿灭的话最好能加上本周有没有刷满的检查（识别左下角数字就行了）
- 软件退出的时候如果 adb 没释放的话、可不可以直接杀死进程呢？只要关联了启动 adb 的进程PID、直接在退出软件的时候杀死对应的 adb 进程然后再完全退出软件就好了
- 附件的提示音是原来自己写脚本的时候编辑好的、当然哪个方案更好用哪一个（虽然觉得自定义的提示音更好听_(:з」∠)_

**Comment by MistEO** [comment]
最新测试版已新增部分常用关卡选择功能、任务全部完成提示；同时修复了`adb`不释放的问题

**Comment by usaginya** [comment]
> 最新测试版已新增部分常用关卡选择功能、任务全部完成提示；同时修复了`adb`不释放的问题

辛苦啦、如果有其他问题以后看情况再提

**Comment by usaginya** [comment]
> 最新测试版已新增部分常用关卡选择功能、任务全部完成提示；同时修复了`adb`不释放的问题

试了最新测试版在任务全部完成时提示阶段程序未响应了、直接弹出已停止工作
![截图1221224736](https://user-images.githubusercontent.com/16422300/146949175-bb5c3514-7325-4655-95ae-813acd6c31af.jpg)

**Comment by MistEO** [comment]
这是Win7么？

这个通知用的是 Win10 的组件，可能确实有问题。。回头我想想咋整_(:з」∠)_

**Comment by usaginya** [comment]
> 这是Win7么？
> 
> 这个通知用的是 Win10 的组件，可能确实有问题。。回头我想想咋整_(:з」∠)_

适配 Win7 的话可以用简单的提示，比如托盘图标气泡通知什么的就可以，毕竟 Win7 也淘汰了，不用花太多精力适配。。不过好像软件也没有托盘图标的功能，不知道会不会更麻烦。。(^ω ^ " )
