### ISSUE TITLE
软件打开闪退

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistantArknights#76]
目前只有2.3.6正常运行，之后版本都是打开后闪退，没有日志，每次更新都下载下来试，但是到目前还是闪退_(:з」∠)_本人小白，想问下有没有啥解决方案，用这个软件好久了，还想抢救下_(:з」∠)_跪谢
（附：火绒剑扫的应用进程，不过貌似没啥卵用）
[MeoAsstGui.txt](https://github.com/MistEO/MeoAssistantArknights/files/7763553/MeoAsstGui.txt)

**Comment by MistEO** [comment]
你是AMD的cpu么，是的话有可能_(:з」∠)_

后面的版本更新了飞桨OCR，不清楚是不是对Intel有什么特殊依赖

可以试着用cmd启动下，看看报啥错？

**Comment by MistEO** [comment]
方便的话加下Q群吧，672372860，到时候我编几个版本，帮忙验证下有没有用

**Comment by guojunyu196** [comment]
QQ私您了，还有问下游戏cmd是啥_(:з」∠)_

**Comment by guojunyu196** [comment]
QQ私您了，还有问下游戏cmd是啥_(:з」∠)_

**Comment by MistEO** [comment]
已提供兼容方案，请参考 [可能性 2: CPU 指令集不支持](https://github.com/MistEO/MeoAssistantArknights/tree/dev#%E8%BD%AF%E4%BB%B6%E4%B8%80%E6%89%93%E5%BC%80%E5%B0%B1%E9%97%AA%E9%80%80) 进行操作
