### ISSUE TITLE
可否适配linux?或者提供一下编译教程？

### ISSUE THREAD

**Issue by proItheus** [MistEO/MeoAssistantArknights#78]
如题，我平时主力系统为arch,想知道能否在realease里提供一个linux的可执行文件，比如appimage啥的。或者能考虑提供一下编译教程吗？我把代码拉到本地直接编译会报错，好像是少了几个lib。多谢！
`MeoJson_LIB
    linked by target "MeoAssistant" in directory /home/proitheus/Documents/MeoAssistantArknights
Opencv_LIB
    linked by target "MeoAssistant" in directory /home/proitheus/Documents/MeoAssistantArknights
PaddleOCR_LIB
    linked by target "MeoAssistant" in directory /home/proitheus/Documents/MeoAssistantArknights
Penguin_LIB
    linked by target "MeoAssistant" in directory /home/proitheus/Documents/MeoAssistantArknights
`

**Comment by MistEO** [comment]
少的几个 lib 是第三方库，在`3rdparty`里，但是我只编了 win32 版本。长期计划是有适配 linux 的打算的，短期内可以试试隔壁 [AAH](https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper)

**Comment by MistEO** [comment]
初步完成了跨平台移植，简单整了个[文档](https://github.com/MistEO/MeoAssistantArknights/blob/cross_platform/src/MeoAssistant/Linux%E7%BC%96%E8%AF%91%E6%95%99%E7%A8%8B.md)，后面我再进一步完善下_(:з」∠)_
