### ISSUE TITLE
MuMu模拟器2.5.16版本 任务异常

### ISSUE THREAD

**Issue by Aberstone** [MistEO/MeoAssistantArknights#79]
模拟器:MuMu
模拟器版本:2.5.16
模拟器启动器版本:2.4.6
Bug内容：在1920*1080 DPI 360 / 默认1280*720/默认 1440*810 分辨率下，领取日常奖励以及访问好友会出现任务出错
任务异常截图：
![image](https://user-images.githubusercontent.com/37994669/147397791-d6dfacca-14a5-4c20-a23d-a8e808f98789.png)
Log文件:
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7776482/asst.log)

**Comment by MistEO** [comment]
是卡在跨年纪念签到活动的那个界面了么？

**Comment by Aberstone** [comment]
> 是卡在跨年纪念签到活动的那个界面了么？

日常任务：卡在主界面上，而且进程是没有卡死的，手动点击进入日常界面会自动返回主界面。
开始唤醒：能够通过黄色按钮的start和开始唤醒，进入主界面之后无法识别到已经进入主界面了（没有签到活动

**Comment by Aberstone** [comment]
> 是卡在跨年纪念签到活动的那个界面了么？

刚又试了一下，公招也是会卡在主界面无法进入公招界面，应该是在主界面上识别有点问题。

**Comment by MistEO** [comment]
`1440x810`这个分辨率有点怪，换`1280x720`或者`1920*1080`试看看？

**Comment by Aberstone** [comment]
> `1440x810`这个分辨率有点怪，换`1280x720`或者`1920*1080`试看看？

都试过的，内部的逻辑基本都正常，就是在主界面进不去 公招/基建 页面

**Comment by MistEO** [comment]
> > `1440x810`这个分辨率有点怪，换`1280x720`或者`1920*1080`试看看？
> 
> 都试过的，内部的逻辑基本都正常，就是在主界面进不去 公招/基建 页面

太怪了，完全没有识别得分和结果，一般就算分辨率不正确也应该有个不到阈值的得分的 orz 有点不知道是啥问题了

如果愿意的话要不再换个模拟器试试，不知道和 mumu 的渲染方式是不是有关系

**Comment by Aberstone** [comment]
> > > `1440x810`这个分辨率有点怪，换`1280x720`或者`1920*1080`试看看？
> > 
> > 
> > 都试过的，内部的逻辑基本都正常，就是在主界面进不去 公招/基建 页面
> 
> 太怪了，完全没有识别得分和结果，一般就算分辨率不正确也应该有个不到阈值的得分的 orz 有点不知道是啥问题了
> 
> 如果愿意的话要不再换个模拟器试试，不知道和 mumu 的渲染方式是不是有关系

OK，那这个ISSUE就先关闭吧（一定是米哈游干的
