### ISSUE TITLE
碎石bug

### ISSUE THREAD

**Issue by Blood-thirsted** [MistEO/MeoAssistantArknights#84]
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7781980/asst.log)

都没勾选碎石还是碎了三个石头（前两个没截图，停止重开还是又碎了一个）
mumu模拟器2.6.7.0
![MeoAsstGui_Tb6S1NO8Zn](https://user-images.githubusercontent.com/61890771/147512445-9fb26303-c16e-49cc-a6a1-a8846a4c5035.png)
![MeoAsstGui_3fAewIyYCa](https://user-images.githubusercontent.com/61890771/147512450-612fdfee-5044-4f6f-9186-869fd31874f2.png)

**Comment by MistEO** [comment]
是的，v2.5.6 新引入的 bug，已经撤包了，不好意思_(:з」∠)_先用 v2.5.5 吧

**Comment by MistEO** [comment]
[v2.5.7](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.5.7) 已修复~
