### ISSUE TITLE
捕获模拟器窗口失败

### ISSUE THREAD

**Issue by a78239636** [MistEO/MeoAssistantArknights#85]
模拟器：mumu模拟器
问题：
![image](https://user-images.githubusercontent.com/34701894/147659387-50a489f1-32a5-4443-82a5-c0705dc723ee.png)
日志：
[asst.log](https://github.com/MistEO/MeoAssistantArknights/files/7788686/asst.log)

顺便想问下：软件更新的代理配置，配的是socks5的还是 http的

**Comment by MistEO** [comment]
- 连接错误，请参考 [README](https://github.com/MistEO/MeoAssistantArknights#%E8%BF%9E%E6%8E%A5%E9%94%99%E8%AF%AF%E6%8D%95%E8%8E%B7%E6%A8%A1%E6%8B%9F%E5%99%A8%E7%AA%97%E5%8F%A3%E9%94%99%E8%AF%AF)
- 仅支持`http`
