### ISSUE TITLE
软件闪退问题和一点小建议

### ISSUE THREAD

**Issue by 1756444066** [MistEO/MeoAssistantArknights#91]
今天在刷雪境本的时候“方舟助手”出现了闪退情况，重启模拟器和“方舟助手”后仍存在闪退情况，第一次闪退是在刷到第三把的结算界面，第二次闪退是在信用商店界面

顺便提一点小建议，能否让玩家自己保存两套宿舍干员配置用于宿舍换班

模拟器版本：MuMu 2.6.7.300
已将文件夹进行打包：www.ljxstudio.com/files/meo.rar

**Comment by MistEO** [comment]
- 感谢反馈，应该是`v2.6.2`新引入的问题，排查修复中_(:з」∠)_ 在此之前可以先使用`v2.6.1`
- 自定义换班，短期内应该不好弄，因为软件是识别干员技能，而不是干员名字，~~有谁会记得所有技能名然后挨个配置呢~~。长期计划的话就属于新建文件夹了（

**Comment by 1756444066** [comment]
还是非常感谢大佬开发的方舟助手，辛苦了！
过几天考完试一定去看直播！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MistEO/MeoAssistantArknights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MistEO/MeoAssistantArknights] 软件闪退问题和一点小建议 (Issue #91)





  
感谢反馈，应该是v2.6.2新引入的问题，排查修复中_(:з」∠)_ 在此之前可以先使用v2.6.1
 
自定义换班，短期内应该不好弄，因为软件是识别干员技能，而不是干员名字，有谁会记得所有技能名然后挨个配置呢。长期计划的话就属于新建文件夹了（
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MistEO** [comment]
- 闪退问题已修复。
- 基建自定义可以跟进 https://github.com/MistEO/MeoAssistantArknights/issues/13 ，不过短期内估计是搞不出来了_(:з」∠)_
