### ISSUE TITLE
基建换班顺序建议

### ISSUE THREAD

**Issue by ylsy2002** [MistEO/MeoAssistantArknights#98]
目前已知的问题，比如可替换干员数不足导致制造站无限循环、宿舍效率较低等问题，可能是基建换班顺序有问题，目前的逻辑是制造站先换，宿舍最后；比较合理的次序应该是首先将心情在阈值以下的干员放宿舍休息，然后再去其他设施换班。

**Comment by MistEO** [comment]
- 可替换干员数不足导致制造站无限循环，这是已知 bug，已有计划修复
- 顺序是可以在设置里拖动调整的，但是即使先放宿舍也没啥用_(:з」∠)_

**Comment by MistEO** [comment]
[测试版本](https://github.com/MistEO/MeoAssistantArknights/releases/tag/v2.7.2) 已修复，请期待正式版~
